### ISSUE TITLE
Improve the extract_data to read custom template when used as a library

### ISSUE THREAD

**Issue by duskybomb** [invoice-x/invoice2data#122]
Currently, templates are read inside `main()` as well as `extract_data()`. Hence, whenever user uses `invoice2data` as an external library in order to use custom template he needs to pass instance of `InvoiceTemplate` which looks like this
```
InvoiceTemplate([('issuer', 'PC Engines GmbH'), ('fields', OrderedDict([('amount', 'Total\\s+EUR\\s+([\\d ,]+.\\d{2})'), ('amount_untaxed', 'Subtotal\\s+EUR\\s+([\\d,]+.\\d{2})'), ('date', 'Date:\\s+(\\d{1,2}\\. \\d{1,2}\\.\\d{4})'), ('invoice_number', 'Invoice\\s+(\\w+)'), ('static_vat', 'CHE-109.825.964'), ('stati c_partner_email', 'orders@pcengines.ch')])), ('keywords', ['CHE-109.825.964', 'Invoice', 'EUR', 'pcengine s.ch']), ('options', OrderedDict([('currency', 'EUR'), ('date_formats', ['%d.%m.%Y']), ('languages', ['en ']), ('decimal_separator', '.')])), ('template_name', 'ch.pcengines.yml')])
```
Hence not very handy to use.
Suggestions:
 * Pass argument for template folder to `extract_data()`
 * read  templates from template folder if defined in `extract_data()`

**Comment by eccentric** [comment]
I didn't find this very well documented, but you can use read_templates which makes this not as bad:

```
from invoice2data import extract_data
from invoice2data.extract.loader import read_templates

templates = read_templates('/path/to/your/templates/')
result = extract_data(filename, templates=templates)
```

templates becomes your list of InvoiceTemplate objects.

**Comment by adrienjacob** [comment]
Exactly, that's what I did and struggled a bit (didn't see @eccentric's suggestion earlier)... I just created PR https://github.com/invoice-x/invoice2data/pull/237 to at least mention the trick in the doc.

**Comment by m3nu** [comment]
#237 is already merged. Closing this issue.
