### ISSUE TITLE
importing `pdfminer` but it is not in requirements.

### ISSUE THREAD

**Issue by Assassinkin** [invoice-x/invoice2data#132]
in `input/pdfminer_wrapper.py` i see that the module pdfminer is being imported but it is not in the requirements

Am I missing something or it should be added in the requirements.

**Comment by m3nu** [comment]
It doesn't work very well and is only optional. So it's not in the requirements.

**Comment by Assassinkin** [comment]
@m3nu  Thanks, Any ETA on when that can be fixed ?

**Comment by m3nu** [comment]
Fix what? We won't put `pdfminer` in the requirements because it's not the default and doesn't work too well compared to `pdftotext`.

**Comment by m3nu** [comment]
If you use `pdfminer` just install it in addition and it will work. We just tested it this week. But we don't like the way it extracts text. Makes it hard to get information out. Since there may be some use cases where people want to use it, we still keep it as optional module.

**Comment by Assassinkin** [comment]
Ahh ok i thought there was an issue on how it is being used (code wise). Thanks for the clarification.

**Comment by m3nu** [comment]
No no. Just trying to keep requirements down. If pdfminer works for you, just keep using it.
