### ISSUE TITLE
Convert Markdown to RST in setup.py

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoice2data#136]
As you know, Python packages are published on PyPi. For this project, this happens after successful builds.

Since PyPi expects Restructured Text files for the readme, our Markdown doesn't look as good. There are some libraries to convert MD to RST. I suggest to use one for conversion to make the page look better. Other projects do the same. Suggest to see what's the best way to implement it.

**Comment by duskybomb** [comment]
Pandoc is a popular one.

**Comment by m3nu** [comment]
Anything that works. Is there any established solution that the user doesn't need to have pandoc installed during installation?

**Comment by duskybomb** [comment]
Why does the user need to have Pandoc installed? We are just converting files from MD to rST, right?

**Comment by m3nu** [comment]
Because the Markdown file is converted in `setup.py`. This file is also called during installation.

We can also do it manually for now. Please just add the command to `DEVELOP.md`.

**Comment by m3nu** [comment]
https://stackoverflow.com/a/23265673

**Comment by duskybomb** [comment]
I tried pandoc, I don't think auto conversion from markdown to rST would be a good idea. It messed up a few bullet points while converting `README.md`.

**Comment by m3nu** [comment]
I guess README.md can be changed to account for that.

**Comment by duskybomb** [comment]
Let me check, how that can be done.

**Comment by duskybomb** [comment]
Now there is one issue, pandoc is not able to convert hyperlinked image (CI badge). (Works if there is no link to CI)

**Comment by m3nu** [comment]
Pure HTML may work. The hyperlink isn't necessary. Just the image will be enough as well.

**Comment by flokli** [comment]
Added a PR converting the README in the repo from markdown to rst, see above.

Conversion at install time is a very spooky and error prone thing IMHO introducing dependencies, so why not simply converting into the format better suited for PyPi for once and be done?

**Comment by m3nu** [comment]
Good point. Let's go with that. Also a good practice to learn editing the Debian Wiki.
