### ISSUE TITLE
Add section on coverage to DEVELOP.rst

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoice2data#139]
This is to see how good our tests are and to help everyone adding tests later.

**Comment by duskybomb** [comment]
I did make a PR #135, if you can check. It will bump up the coverage.

**Comment by duskybomb** [comment]
Coverage is 89% now

**Comment by duskybomb** [comment]
![image](https://user-images.githubusercontent.com/13499577/40583157-596c4d78-61a6-11e8-9a9b-7a8467d92eb2.png)
