### ISSUE TITLE
ERROR:invoice2data.main:No template for invoice2.pdf

### ISSUE THREAD

**Issue by natashakhatib23** [invoice-x/invoice2data#149]
I have installed invoice2data and pdftotext but i'm facing this error whenever i write "invoice2data invoice2.pdf" why?

**Comment by duskybomb** [comment]
This because none of the existing templates match your pdf. You need to create your own template to make it work. You should go through [Tutorial for template creation](https://github.com/invoice-x/invoice2data/blob/master/TUTORIAL.rst)

**Comment by natashakhatib23** [comment]
which means that invoice2data module isn't a general solution for data  extraction of the invoice.
Suppose i have an invoice from an organisation that i didn't create its template yet, it won't get me the data out of it .. right ?

**Comment by natashakhatib23** [comment]
do you think machine learning algorithms would help in extracting data from an invoice with no template ?

**Comment by m3nu** [comment]
Yes. Being done by the guys who got in touch in #148. I didn't test it, so I'm not sure about the accuracy. Since accounting processes generally demand 100% accuracy strict templates that fail when there is any uncertainty are possibly preferable for now.

In the medium term we strive to embed the invoice data directly and skip all the recognition. See [this other project](https://github.com/invoice-x/factur-x) we are working on for details.

**Comment by darkar18** [comment]
same i am having same issue: using invoice2data module which i ran using : invoice2data --input-reader tesseract --template-folder \invoice2data\src\invoice2data\extract\templates aug.pdf

issuer: VILANGATTIL HARDWARES
keywords:
  - ERUVELI, CHOTTANIKKARA
  - 32AKUPJ3251Z4
fields:
  amount: (\d+)
  date:
    (\d{2})+\/+(\d{2})+\/+(\d{4})
  invoice_number: Invoice No.
 
    (\d{4})+\-+(\d{2})+\/+(.*[A-Z][0-9]+)
options:
  remove_whitespace: false
  date_formats:
    - '%d/%m/%Y'
lines:
    start: \#Item\snameHSN\/SACQuantityUnitPrice\/unitGSTAmount
    end: Total
    body: (?P<list>^\d{1,2})+\s+(?P<product>.*[A-Z])+\s+(?P<HSN>\d{4,8})+\s+(?P<quantity>\d+)
    
![Annotation 2021-09-14 211733](https://user-images.githubusercontent.com/65691792/133290813-854f2f21-c90c-4359-937b-56022cc71a06.png)

attaching: sample invoice for your reference

**Comment by rmilecki** [comment]
@darkar18: please run `invoice2data` command with `--debug` switch and paste or attach the output. You can replace private data with starts or something.

**Comment by kavin2532** [comment]
add "issuer" value in yml file from one of the main string in PDF file
