### ISSUE TITLE
Is it possible to extract data from an image (PNG of JPG)?

### ISSUE THREAD

**Issue by sulaymankhan** [invoice-x/invoice2data#150]
Is it possible to extract data from an image (PNG of JPG)?

**Comment by m3nu** [comment]
Yes. Using either Tesseract or the online OCR cloud service. Both are implemented directly.

Just set your templates up for extra stability, as the OCR output may change slightly between runs.

**Comment by sulaymankhan** [comment]
@m3nu Thank you. I tried Tesseract but the results were not very good. I will try DocParser and see how it goes.
