### ISSUE TITLE
Sample code to use as library

### ISSUE THREAD

**Issue by SornaSundaram** [invoice-x/invoice2data#152]
when i tried to extract data from the invoice from test folder by importing invoice2data as library using pdfminer i get this following error ? please help me with this issue .

WARNING:root:regexp for field amount didn't match
WARNING:root:regexp for field invoice_number didn't match
WARNING:root:regexp for field payment_method didn't match
ERROR:root:Unable to match some fields:

**Comment by duskybomb** [comment]
It means that the text is not matching the defined field's regular expression. Just go through [Template Tutorial](https://github.com/invoice-x/invoice2data/blob/master/TUTORIAL.rst) to know how to write a template.

**Comment by SornaSundaram** [comment]
Sir i had tested the scenario for the sample pdf file already provided ("oyo invoice") in the package. All the files in the compare folder u had ran for it but i dont know where i am doing wrong . Thanks for your response sir

**Comment by duskybomb** [comment]
The reason for this is all most of the templates are made for use with `pdftotext`. The "OYO invoice" is also based on `pdftotext` output.

**Comment by m3nu** [comment]
Post your full code. I'm certain this is about paths and imports.
