### ISSUE TITLE
How the code finds the right matching template or Will it compare with every existing template ?

### ISSUE THREAD

**Issue by SornaSundaram** [invoice-x/invoice2data#153]
Suppose if i am trying to extract data from the invoices ? will it check with every existing template for a match or how it will find the right template ?

**Comment by chriswakare** [comment]
> Template files are tried in alphabetical  order
from https://github.com/invoice-x/invoice2data#template-system

**Comment by m3nu** [comment]
Right. The first template containing ALL keywords specified in the template is used. Using the tax number + company name as keyword is usually good.

**Comment by SornaSundaram** [comment]
Thanks for helping me .
