### ISSUE TITLE
Windows support for tesseract and pdftotext

### ISSUE THREAD

**Issue by SornaSundaram** [invoice-x/invoice2data#156]
Can I use Pytesseract instead of tessearct for extracting invoice data ? since tesseract not compatible in windows and I am also unable to install pdftotext in windows.

**Comment by m3nu** [comment]
The pytesseract package is [wrapping](https://github.com/madmaze/pytesseract/blob/1b0018f9ccd9ff2c227a21693f1d6155e139dbe2/src/pytesseract.py#L28) the `tesseract` binary, same as we do.

But if you like you can fork the repo and do whatever you want and add a new input module.
