### ISSUE TITLE
Migrate Continuous Integration

### ISSUE THREAD

**Issue by duskybomb** [invoice-x/invoice2data#160]
According to [CircleCI](circleci.com), "Projects currently running on CircleCI 1.0 will no longer be supported after August 31, 2018. Please migrate to CircleCI 2.0."
Hence need to migrate.

**Comment by m3nu** [comment]
Yeah. Also got the email. Not too urgent, but we can't make updates any more. You wanna keep CircleCI or do you recommend another service with less vendor lock-in?

**Comment by duskybomb** [comment]
TravisCI looks like a popular choice. But really don't know how different it is from CircleCI. Will uodate you soon on it.
