### ISSUE TITLE
Add "Must not have" keywords

### ISSUE THREAD

**Issue by Gsuz** [invoice-x/invoice2data#164]
I'm having trouble creating templates to distinguish between a normal invoice and a credit invoice.

I suggest adding an option for banned keywords so that it would try the next template. It could also help in other niche use cases.

**Comment by irahulcse** [comment]
Want to work on this project. How can  I start working as I am new to Open Source.

**Comment by m3nu** [comment]
Start by forking this repo to your own Github account and then clone it to your local machine. The do a dev-install via `pip install -e .` as described in the [DEVELOP](https://github.com/invoice-x/invoice2data/blob/master/DEVELOP.rst) document.

Next implement the feature and open a pull request (PR) that has your changes. If the code is OK one of the contributors (or me) will merge it.

**Comment by irahulcse** [comment]
Tnx sir

**Comment by Gsuz** [comment]
I have a crude implementation of this in : #165

**Comment by wollanup** [comment]
This is a "must have" feature :smile:

**Comment by rmilecki** [comment]
Implemented in the https://github.com/invoice-x/invoice2data/pull/330
