### ISSUE TITLE
Language as a input parameter

### ISSUE THREAD

**Issue by suryacaprice** [invoice-x/invoice2data#181]
I can see the default language is french. But can you please provide option to enter language as input so that english or other languages can be switched easily .

**Comment by m3nu** [comment]
Where is French the default language?

**Comment by m3nu** [comment]
I see. Yeah. I did this for a French client.

If you want an option, just open a pull request and I'll review it.

**Comment by suryacaprice** [comment]
Sure will do

**Comment by knutole** [comment]
Any progress on this? Very useful to be able to pass language to tesseract for example.

**Comment by bosd** [comment]
This is a tricky problem to tackle. As one have to know and input the language before the rpcessing takes place.
It quickly leeds to a complicated pipline
[Preprocess image (ocr) to determine language](https://github.com/JAIJANYANI/Language-Detection-in-Image) --> match detected words against dictionary to guess language --> process the file again with the guessed (detected)  language.



I would like to propose a more simple solution.
Set the default language to English. (as it is internationally much more common then french.)
Poll which additional tesseract ocr languages are installed by the user.

Process the document with the default language + all the installed languages of the user. 
Tesseract will then use the language which will best fit the image.



Proposed solution will work for tesseract, as it is used in the [OCR mypdf](https://github.com/ocrmypdf/OCRmyPDF/tree/master/src/ocrmypdf) project.

https://github.com/ocrmypdf/OCRmyPDF/blob/3dfde479e2d0d6dac4c6f55093038068e475b82c/src/ocrmypdf/builtin_plugins/tesseract_ocr.py#L154-L155

**Comment by bosd** [comment]
Fixed by the above 2 PR's
