### ISSUE TITLE
PDF's with Multiple pages/totals

### ISSUE THREAD

**Issue by JeffreyGarand** [invoice-x/invoice2data#189]
Running into an issue with PDF's with 'multiple pages'. The system is picking up multiple invoice numbers but not multiple totals. 
 Please advise.

**Comment by JeffreyGarand** [comment]
Thanks @rseabrook  I'll give that a try.

**Comment by amitava82** [comment]
I'm seeing this as well. I have multiple invoices in single pdf. I'd expect it to create array of results per page. It returns invoice_number as array. Everything else looks like picked from first page.

**Comment by m3nu** [comment]
Multiple invoices in one document will surely not work.

**Comment by AshNTU** [comment]
Hi, I am also facing the same problem. Is there a way for the invoice2data to identify that the file contains multiple invoices, so that it can be handled accordingly?

**Comment by rseabrook** [comment]
@AshNTU this is not the way invoice2data is designed to work. Each file needs to represent one invoice.

The package allows multiple regexes for a particular field and collects the results of every regex into a list for that field. It then attempts to pick the best result by discarding any empty strings and duplicates. If that leaves only one result, then invoice2data returns that result as a string. If there are multiple results, it returns a list of all of them. It is then the user's responsibility to decide which result is the best one. This is the "deduping" process I referred to in the comment above from January. invoice2data is actually picking up multiple invoice numbers AND multiple totals, it just condenses the totals into a single value before returning the result. This is done in an attempt to make life easier on the user when there are repeated values for the same field. I don't want to speak for @m3nu, but I don't think this behavior should or will change.

You could get invoice2data to break a file into multiple invoices by defining some text (or a regex) that can show invoice2data where one invoice ends and another begins. Then invoice2data could run each chunk of text through the extraction process. It would only work when all of the invoices in a file follow the same template.

I would encourage one of you who has this issue to dig into the source, understand how invoice2data works, and write a script to do this that we can include as an example in the docs!

**Comment by AshNTU** [comment]
Thanks @rseabrook for the clarification. I am not sure if we have this feature in invoice2data

> You could get invoice2data to break a file into multiple invoices by defining some text (or a regex) that can show invoice2data where one invoice ends and another begins. Then invoice2data could run each chunk of text through the extraction process. It would only work when all of the invoices in a file follow the same template.

I looked through the doc but could not find any documentation for this. Please let know how to use this feature, if it is available.

**Comment by rseabrook** [comment]
@AshNTU like I said on the first line, invoice2data is not designed to work that way currently. You would have to hack it together yourself.

**Comment by m3nu** [comment]
> invoice2data is not designed to work that way currently

Absolutely correct. Currently we expect 1 file = 1 document/invoice.

If you have a way to split your files, you can just write some temp files and run `invoice2data` on those. The first part could be hard to get right. The second part is easy.

**Comment by SNavgale** [comment]
I have achieved this by doing pre-processing and creating temp pdfs one per page using pyPDF2 and then processing them in a loop, works fine.
