### ISSUE TITLE
Unable to parse invoice lines

### ISSUE THREAD

**Issue by sonalimore35** [invoice-x/invoice2data#195]
I am using your library to extract the invoice information in json format. I got other information from invoice like invoice_number,date etc, but **I am unable extract invoice  lines.**
I tried many solutions which are found on google but no luck. **I also tried debug option** while running command through terminal.

I am also facing one more issue while parsing amount, actually it's a warning but even though I am not able to read amount.

**It would be really grateful for me if you help to come out from this issue. Your help and response is highly appreciated.**
 
**python version: 2.7**
** Ubuntu 16.04**

**Comment by sonalimore35** [comment]
@m3nu can you help me please?

**Comment by m3nu** [comment]
Sorry, but Github issues are just for bugs, not for support. If you need help with a programming job, you can look into hiring some external help. We should add a list of companies that can help you implement `invoice2data`. For now, you can send an enquiry to my company at [peakford.com](https://www.peakford.com/).
