### ISSUE TITLE
List of commercial service providers

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoice2data#196]
Too many people are asking for support to implement this. I suggest to add a list of commercial service providers, who can help them on a consulting basis. Whoever is interested, can leave his details here. You should already be a contributor and willing to accept new clients.

Calling some past contributors: @alexis-via @hbrunn @rseabrook @brakhane

**Comment by hbrunn** [comment]
not us, we're user/contributors

**Comment by m3nu** [comment]
> not us, we're user/contributors

Noted. Maybe we can find 2-3 firms, who are willing to offer some commercial support. Would be easier to just refer people to them.

**Comment by m3nu** [comment]
Great @brakhane . I'd add website, company name, tag line. Similar to another project [here](https://www.borgbackup.org/support/commercial.html).

**Comment by brakhane** [comment]
@m3nu Should I make a PR with the information? Where should I put it? Into the README?

**Comment by m3nu** [comment]
Just post it in this issue. I will make a new mardown document when we’re done.

**Comment by brakhane** [comment]
inoio gmbh
https://inoio.de
contact@inoio.de (German and English)
