### ISSUE TITLE
how to use tesseract with your library

### ISSUE THREAD

**Issue by auriou** [invoice-x/invoice2data#204]
Hello

how to use tesseract with your library.

I installed tesseract with   pip install tesseract but not work

````
$ invoice2data --template-folder . --debug --input-reader tesseract invoice.pdf
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\Scripts\invoice2data-script.py", line 11, in <module>
    load_entry_point('invoice2data==0.3.2', 'console_scripts', 'invoice2data')()
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\invoice2data\main.py", line 166, in main
    res = extract_data(f.name, templates=templates, input_module=input_module)
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\invoice2data\main.py", line 90, in extract_data
    extracted_str = input_module.to_text(invoicefile).decode('utf-8')
  File "c:\users\user\appdata\local\programs\python\python36-32\lib\site-packages\invoice2data\input\tesseract.py", line 21, in to_text
    raise EnvironmentError('tesseract not installed.')
OSError: tesseract not installed.
````

Thx

**Comment by m3nu** [comment]
Tesseract is not a Python package. You only installed a wrapper library. See [here](https://github.com/tesseract-ocr/tesseract#installing-tesseract) to install the underlying binary.

**Comment by JonhSilver** [comment]
I have ssame issue, tesseract is 1000% installed, but i got this error

**Comment by bosd** [comment]
> I have ssame issue, tesseract is 1000% installed, but i got this error

Are you also on a Windows system?

**Comment by JonhSilver** [comment]
Yes

**Comment by JonhSilver** [comment]
I think problem here in tesseract.py 
where in windows you should provide path to exe, so need to change this part

if not spawn.find_executable("tesseract"):
to
if not spawn.find_executable(pathtoTesseract_exe):

also extract module is not work like expected

result =   extract_data(pathname, read_template, tesseract)
is produce error NameError: name 'tesseract' is not defined

result =   extract_data(pathname, read_template, "tesseract")
will produce error 
AttributeError: 'str' object has no attribute 'to_text'

so only one way is change manually main.py def extract_data  or redeclare imports

**Comment by JonhSilver** [comment]
so need changes in **invoice2data\input\tesseract.py**
**line 4**
change:
`def to_text(path):`
to
`def to_text(path, input_module_path):`
**and line 41:**
from
`tess = [input_module_path, "stdin", "stdout"]`
to
`tess = [input_module_path, "stdin", "stdout"]`


so need changes in **invoice2data\main.py**
**line 35**
from
`def extract_data(invoicefile, templates=None, input_module=tesseract):`
to
```
ScriptPathWithName = os.path.abspath(__file__) 
CurrentFolderPath = os.path.dirname(ScriptPathWithName) 

def extract_data(invoicefile, templates=None, input_module=tesseract, input_module_path=CurrentFolderPath):
```
**line 81**
from
   ` extracted_str = input_module.to_text(invoicefile).decode("utf-8")`
to
   ` extracted_str = input_module.to_text(invoicefile, input_module_path).decode("utf-8")`


and after you can do in your python file

from invoice2data.input import tesseract
ScriptPathWithName = os.path.abspath(__file__) 
CurrentFolderPath = os.path.dirname(ScriptPathWithName) 
pytes = os.path.join(*[CurrentFolderPath, "src", "Tesseract-OCR", "tesseract.exe"]) # here path to your tesseract install 
result =  extract_data(pathname, read_template, tesseract, pytes)
