### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by arthur-b-renaud** [invoice-x/invoice2data#206]
In the first line : 
"This project has been selected for GSoC 2018. Read more here (https://wiki.debian.org/SummerOfCode2018/Projects/ExtractingDataFromPDFInvoicesAndBillsDetails)"

The link in parenthesis seems broken.

**Comment by m3nu** [comment]
Works fine here. Maybe a temporary issue, as Debian was updating their Wiki.

But it should be removed anyways, because it's from last year.
