### ISSUE TITLE
Table that has no end

### ISSUE THREAD

**Issue by mmaaxxtbg** [invoice-x/invoice2data#207]
Hi All,

first up, sorry if this should not be posted - but trying to learn this as best as I can

I am trying to match the following invoice which end like this 
`SUPPLIED PARTS, OR DAMAGED GOODS OVER 7 DAYS AFTER RECEIPT ARE NOT RECOGNISED.            GST                Total
RETURNS NEED APPROVAL & ARE SUBJECT TO A 10% HANDLING CHARGE.
NO CLAIMS RECOGNISED 30 DAYS AFTER DATE OF DELIVERY .                 Page:    2        349.01            3,839.11

DEBUG:root:END optimized_str ==========================
`
What is the bast way to GST and the Total value out of this?
Note : it is not always page 2 in the invoice

**Comment by rseabrook** [comment]
Github issues are for bugs, not support requests.

However, this case should be straightforward. You can try adding these to your template:

`gst: Page:\s+\d+\s+((?:\d{1,3})?(?:,\d{3})*(?:.\d{2})?)\s+(?:\d{1,3})?(?:,\d{3})*(?:.\d{2})?`
`total: Page:\s+\d+\s+(?:\d{1,3})?(?:,\d{3})*(?:.\d{2})?\s+((?:\d{1,3})?(?:,\d{3})*(?:.\d{2})?)`

Assuming these always occur right after the page number, you don't need to use the `tables` plugin for this.

**Comment by mmaaxxtbg** [comment]
Thanks, however we gave up and wrote our own which works for us.
