### ISSUE TITLE
Support for multiple lines using lines plugin

### ISSUE THREAD

**Issue by eddb7** [invoice-x/invoice2data#224]
Hi all, I have been using this package over the past couple of days for some complex invoices for my company, I think this has been raised previously but adding the functionality to define multiple lines within the .yml would be really useful as I need to gather different information from different sections within the same invoice -- tables aren't necessarily well defined structurally on the examples I have been working with as I would of used this approach.

Was there reasoning in only allowing one line definition ( best practice to use multiple .yml to scrape an invoice?), If not I do not mind forking and trying to solve this problem.

**Comment by m3nu** [comment]
This already exists from what I know. And it's configured with each template in YML. Here 2 examples:

- https://github.com/invoice-x/invoice2data/blob/master/src/invoice2data/extract/templates/de/de.qualityhosting.yml
- https://github.com/invoice-x/invoice2data/blob/master/src/invoice2data/extract/templates/com/com.amazon.aws.yml

Note the `lines` section.

**Comment by eddb7** [comment]
Yeah I have successfully setup single applications of line scraping like your example - what I am trying to achieve though is defining multiple different line types for both different data and different line formats.

**Comment by m3nu** [comment]
This we don't have. But maybe you can refactor the existing module to do what you need and we merge it back?

**Comment by eddb7** [comment]
Ok I will have a look into this. Thanks for speedy response

**Comment by eddb7** [comment]
I've added a base solution to this  branch

eddb7:feature/eb-multiple-lines

**Comment by rmilecki** [comment]
This is supported since https://github.com/invoice-x/invoice2data/pull/308

You can use `fields` and multiple entries with `parser: lines`.
