### ISSUE TITLE
Extracting table from pdf

### ISSUE THREAD

**Issue by gosemathraj** [invoice-x/invoice2data#226]
i am trying to extract table data from pdf. I have created a template for the same but it is not giving appropriate column value
This is the table i am trying to extract :
[https://i.imgur.com/6hv728l.png](url) 

Template for extracting table data : 
issuer: XXXXXX
fields:
  amount: Grand Total\s+(\d+\,\d+\.\d+)
  invoice_number: INVOICE No:\s+(\S+)
  date: Date of Invoice:\s+(\S+)
  vendor: Vendor:\s+(\S+)
  sono: SO No:\s+(\S+)
  vehicleno: Vehicle No:\s+(\d+)
keywords:
  - Vendor
  - Automotive
tables:
  - start: Sr.\s+Customer Part No /\s+HSN \/\ SAC
    end: CGST Value In Words
    body: (?P<sr_no>(\d+))\s+(?P<part_no>[\S]+)\s+(?P<hsn_no>(\d+))

options:
  currency: INR

Just consider the tables section.The output i am getting is:
[
    {
        "amount": 177081.32,
        "currency": "INR",
        "date": "04/09/2018",
        "desc": "Invoice from XXXXX",
        "invoice_number": "1232",
        "issuer": "XXXXX",
        "sono": "10384",
        "vehicleno": "123",
        "vendor": "DL",
	"sr_no": "00",                                         // Table data
	"hsn_no": "310082",                            // Table data
	"part_no": "EA"                                     // Table data 
    }
]

The table data values i am getting is mismatch
Here i am getting column 2 values in column 1 and column 3 value in column 2 and so on...
Please help...

**Comment by rseabrook** [comment]
This is not a bug, just a problem with your table regex. Take a look at how your regex matches the table you sent in this [regex debugger tool](https://regex101.com/r/d1gsbO/1). You can see that invoice2data is working exactly as expected given your regex definition.

@m3nu this can be closed.
