### ISSUE TITLE
can't read same format pdf invoices 

### ISSUE THREAD

**Issue by Ritesh260397** [invoice-x/invoice2data#227]
Only your default flipkart invoice(pdf) is fetched  by your flipkart yml template. But when I try to test  your yml template with different flipkart invoice(pdf) having same format, almost same billing ,it only fetches 2-3 details not fetching the main 'order_id'.It only shows this error even though the 'order_id' code is commented.

**Comment by m3nu** [comment]
If you have different invoice formats, you can contribute a new template by opening a pull request.
