### ISSUE TITLE
question about contribution

### ISSUE THREAD

**Issue by jonatjano** [invoice-x/invoice2data#228]
Hi,
just found a way to get better results using tesseract but I'm not sure about something in the contribution guide.

the contribution guide say to 
```
    Fork main repository (optional)
    Clone repository: git clone https://github.com/m3nu/invoice2data
    Install as editable: pip install -e invoice2data
```
but I could edit the project doing `pip install invoice2data` (I modified the files in python/dist-packages) is there a difference for pip ?

TL;DR : sorry I never used pip before and I'm not sure I understand the `-e` utility

**Comment by rseabrook** [comment]
You can read about editable installs in the [pip docs](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs).

This has more to do with git than pip though. The project in `python/dist-packages` is a copy of the package (as it existed when you installed it), but it is not a git repo. If you clone the repo and then install it as editable, you can make edits inside of the git repo, commit them, and push them back here to github so they can be reviewed and merged. You can also easily pull changes from github to update your local copy of the package.

**Comment by m3nu** [comment]
Yeah. You need to clone the repo, open a pull request and we'll merge it.

The process is the same for all projects and Github and it's well documented.

For small changes, you can post the code here and I'll do the PR, if the change is important.
