### ISSUE TITLE
Unable to parse invoice 

### ISSUE THREAD

**Issue by anujarout** [invoice-x/invoice2data#233]
Hi 
I am trying to use invoice2data for parsing some invoices, but i am facing following error:

from invoice2data import extract_data
result = extract_data('XYZ.pdf')

**Output :**
ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 312

*I am not trying any template format.

**Comment by rmilecki** [comment]
Solved by 6ab31047386a ("Treat all YAML templates files as UTF-8 encoded")

Make sure your .yml template file is UTF-8 encoded.

See https://github.com/invoice-x/invoice2data/pull/449
