### ISSUE TITLE
Is there any way to auto generate templates?

### ISSUE THREAD

**Issue by kiranbudati** [invoice-x/invoice2data#236]

**Comment by m3nu** [comment]
With enough sample data, one could train a neural net to do it. If you are looking to do research in this area or can provide the training data, I'd be interested in getting involved.

**Comment by m3nu** [comment]
An interesting article expanding on this. With this, we can partially automate template creation and we could e.g. find invoice numbers with a certain format or dates.

https://nanonets.com/blog/ocr-with-tesseract/

**Comment by johnsmithm** [comment]
hi, I am looking to do research in this area, can you provide the training data? I'd be interested in getting involved.

**Comment by ocr-avenger** [comment]
I found these guys doing automatic templates generation quite successfully https://scandocflow.com

**Comment by bosd** [comment]
I found this project. It is using ML for field detection. Could this one be added as one of the parsers?
https://github.com/naiveHobo/InvoiceNet

**Comment by rmilecki** [comment]
We don't have enough manpower to implement such solution as part of this project. I also think it's out of scope of the `invoice2data`. See also https://github.com/invoice-x/invoice2data/issues/361
