### ISSUE TITLE
output is not getting ,throwing a error while printing

### ISSUE THREAD

**Issue by ganeshsingamaneni** [invoice-x/invoice2data#239]
this is the error
 'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0082: special characters are not allowed
  in "<unicode string>", position 46
----------------
my code:
-----------
from invoice2data import extract_data

result = extract_data('/home/ganesh/Videos/1.pdf')
print(result)

**Comment by m3nu** [comment]
Maybe an old Python version or other issue with Unicode.

**Comment by rmilecki** [comment]
Solved by 6ab31047386a ("Treat all YAML templates files as UTF-8 encoded")

Make sure your .yml templates file is UTF-8 encoded.

See https://github.com/invoice-x/invoice2data/pull/449
