### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mezhossain** [invoice-x/invoice2data#242]
I've been using the upwork template and an upwork invoice to test out this software. I've tried using different input modules such as pdftotext and tesseract.

My code is as follows:

```
from invoice2data import extract_data
from invoice2data.extract.loader import read_templates
result = extract_data('upwork.pdf', templates='com.upwork.yml')
```

I keep getting the same error no matter which input module I use:

```
 Traceback (most recent call last):
  File "N:\python\invoice2data\invoice.py", line 3, in <module>
    result = extract_data('upwork.pdf', templates='com.upwork.yml')
  File "C:\Users\mehraz.hossain\AppData\Local\Programs\Python\Python37\lib\site-packages\invoice2data\main.py", line 92, in extract_data
    optimized_str = t.prepare_input(extracted_str)
AttributeError: 'str' object has no attribute 'prepare_input'
```

Can someone please show me where the error in my code might be?

**Comment by m3nu** [comment]
(fixed formatting of initial comment)

You need to load the template(s) first using the `read_templates()` function. You are passing a string instead, which fails. See the example code on the frontpage for a working example.
