### ISSUE TITLE
output format in json doesn't double quote strings(as per standard).

### ISSUE THREAD

**Issue by rmNULL** [invoice-x/invoice2data#243]
The json output format doesn't follow the standard(mentioned at http://www.json.org/).
(usage of single quotes over double quotes, date in python datetime specific format).

It appears that we get a python dictionary as output when asking for a json.

This commands produces the output given below
```bash
invoice2data --output-date-format "%b-%d-%Y" --template-folder templates/ --output-format json invoice-samples/inv-good.pdf
```

```python
INFO:invoice2data.main:{'issuer': 'XX', 'amount': 83991.44, 'date': datetime.datetime(2019, 7, 8, 0, 0), 'invoice_number': 'YYYYYY', 'currency': 'USD', 'desc': 'Invoice from XX'}
<class 'module'>
<module 'json' from '/usr/lib/python3.6/json/__init__.py'>
```

Also note that, despite passing `--output-date-format` it shows as `datetime` date.
Which is not the desired behavior for someone expecting a json.

Thanks :)

**Comment by m3nu** [comment]
Looks like a misunderstanding. The output you are showing here are the logs. They are not json, but Python dicts.

The actual json is saved to the file you specify :-)

**Comment by rmNULL** [comment]
oh sorry, thanks for pointing it out.
