### ISSUE TITLE
Tables won't match

### ISSUE THREAD

**Issue by digi-talo** [invoice-x/invoice2data#258]
I have the following table
```
Invoice Date:	Due Date:	Source:	Reference:
07/17/2019	08/16/2019	SO1972	INV/2019/1189/25
```
yaml file:
```
- start: Invoice Date:+\s+Due Date:+\s+Source:\s+Reference:
  end: Description
  body: (?P<invoice_date>\d\d\/\d\d\/\d\d\d\d)\s+(?P<due_date>\d\d\/\d\d\/\d\d\d\d)\s+(?P<source>[A-Z]{2}\d\d\d\d)\s+(?P<reference>INV\/\d\d\d\d\/\d\d\d\d\/\d\d)
```
The online regex tester matches all the data but I get the following error:
no table body found - start None, end <_sre.SRE_Match object at 0x7f9299e1c6b0>

Thanks for any suggestions!

**Comment by digi-talo** [comment]
Upon further inspection it seems that it sticks all the fields of each row together so I don't quite understand how to seperate out the different values then.

**Comment by digi-talo** [comment]
Solved, had to disable the remove_whitespace option.
Would be good to add that to the tutorial that this option needs to be disabled in order to be able to use the table plugin

**Comment by rseabrook** [comment]
This is not specific to the tables plugin, just the behavior of the `remove_whitespace` option. That option removes whitespace _before_ running your regex, so your regex needs to expect that. You could have changed your `body` regex to remove the `\s+` tokens to get the matches you want.

**Comment by digi-talo** [comment]
True, I guess it just confused me since I missed the option. Case closed.
