### ISSUE TITLE
Renamed files name structure

### ISSUE THREAD

**Issue by joanjunyent** [invoice-x/invoice2data#26]
It would be great if the filename structure for renamed files could be defined in the template.

**Comment by joanjunyent** [comment]
I think you are right and a command line argument makes more sense since this way you will "normalize" the filename structure making it easier for archiving of further processing.

**Comment by rseabrook** [comment]
@m3nu I know this issue is very old at this point, but I think it is useful and will take it on.

**Comment by bosd** [comment]
Oops, was eyeing this old issue. This one can be closed now
