### ISSUE TITLE
Multiple template for the same VAT number

### ISSUE THREAD

**Issue by rycks** [invoice-x/invoice2data#261]
There is at least two situations where single template for a VAT number is a problem:

- when the provider change his template (for example 2012 invoices are different than in 2019)
- when the provider has more than one trade mark (for example ovh, soyoustart, kimsufi are sharing the same OVH VAT number)

So what could we imagine as solution ?

**Comment by m3nu** [comment]
For situation 1: Have multiple templates with different numbers. Just add a year/version at the end.

Situation 2: Use the VAT number together with another term, like the brand.

**Comment by rmilecki** [comment]
> So what could we imagine as solution ?

Find some words to distinct those invoices and use them in the `keywords`. E.g.
```
keywords:
  - 'VAT: 1231234545'
  - 'Invoice app 2012'
```
```
keywords:
  - 'VAT: 1231234545'
  - 'Invoice app 2019'
```
