### ISSUE TITLE
Types for values fetched using the "tables" key

### ISSUE THREAD

**Issue by rhbvkleef** [invoice-x/invoice2data#263]
If the tables key is used in the template, all resulting values are strings. Many of these are floating point numbers in my case, so I would like the result to contain floating point numbers for these keys.

**Comment by SNavgale** [comment]
Hi rhbvkleefb, How you are using tables key and how you are extracting the values?

regards, S

**Comment by bosd** [comment]
Closing this one. As this is an old issue and code has changed a lot.
Feel free to comment or re-open when this issue still is persists.
