### ISSUE TITLE
Usage example for table plugin

### ISSUE THREAD

**Issue by SNavgale** [invoice-x/invoice2data#270]
I am looking for example usage of table plugin. I am able to use basic extract_data to extract fields from invoice template I have setup using result = extract_data("data/sampleinvoice.pdf", templates=templates)
I have configure template as below for tables as -
tables:
  - start: Charge Description\s+Band\s+Measurement\s+Unit\s+Days\s+Rate\s\(Pence\)\s+Amount
    end: Sub Total Excluding
    body: (?P<charge_description>[\S ]+),\s+(?P<band>[\S]),\s+(?P<measurement>\d+)\s+(?P<unit>\w+)

But not sure how I am supposed to use the table plugin. Is there any example code I can refer to?

**Comment by rmilecki** [comment]
Please provide output of `invoice2data` call with `--debug` option set.

From a quick review that `(Pence)` in your `start` smells fishy. Did you mean `\(Pence\)` or maybe `(Pence)?`?
