### ISSUE TITLE
Detect if . or , is used as decimal separator

### ISSUE THREAD

**Issue by nemiah** [invoice-x/invoice2data#276]
Hello,

I've a fun case where the same company issued two invoices with different decimal separators.

Does anyone have an idea how to parse both of them them correctly?

[Rechnung-GVR443872.pdf](https://github.com/invoice-x/invoice2data/files/4152231/Rechnung-GVR443872.pdf) and [Rechnung-GVR416030.pdf](https://github.com/invoice-x/invoice2data/files/4152232/Rechnung-GVR416030.pdf)

Best wishes
Nena

**Comment by m3nu** [comment]
Ask them to fix their locale settings. 😜

**Comment by nemiah** [comment]
Yes, I agree, that would be the best :grin: 

We could run the text from the PDF file through some kind of pre-processing and fix the numbers…

**Comment by m3nu** [comment]
You can use the library functions directly. The input step is already separate. You can make adjustments before passing it to the extraction step.

**Comment by nemiah** [comment]
I'm currently trying to find out how python works :blush:
