### ISSUE TITLE
No template found when custom template is used and specified

### ISSUE THREAD

**Issue by nickolasclarke** [invoice-x/invoice2data#278]
Hello, 

I am trying to build a custom template to extract data out of PG&E Utility bills. You can see a low resolution screenshot excerpt of the PDF below. (Sorry I couldnt post the original as I needed an easy way to redact details for privacy). 

![bill_screenshot](https://user-images.githubusercontent.com/2177320/76602245-c3889880-64c7-11ea-9d14-06ba251ce60d.jpg)

I have created the following template: 

```yaml
issuer: PG&E
keywords:
  - www.pge.com/MyEnergy
  - 1-800-743-5000
  - www.pge.com/waystopay
  - ENERGY STATEMENT
  - Service For
  - Your Account Summary
  - Ways to Pay
  - Questions about your bill?

fields:
  address: \d+\w+\s+(BLOSSOM STREET)
  kwh_charges: (Current PGE\&E Electric Delivery Charges)\s+\$(\d{1,10}.\d\d)
  ebce_charges: (East Bay Community Energy Electric Generation Charges)\s+\$(\d{1,10}.\d\d)
  gas_charges: (Current Gas Charges)\s+\$(\d{1,10}.\d\d)
  total_kwh:    (Total Usage)+\s+.+(kWh)
  total_therms: (Total Usage)+\s+.+(Therms)
  bill_date_range: (\d{2}\/\d{2}\/\d{4})\s(-)\s(\d{2}\/\d{2}\/\d{4})+(.+billing days\))

options:
 currency: USD
```

when I call `invoice2data 01062020.pdf --output-name test.csv --output-format csv --exclude-built-in-templates --template-folder ~/template/`

it fails with the following:

```
ERROR:invoice2data.main:No template for 01062020.pdf
Traceback (most recent call last):
  File "/home/nclarke/.pyenv/versions/playtime/bin/invoice2data", line 11, in <module>
    load_entry_point('invoice2data==0.3.5', 'console_scripts', 'invoice2data')()
  File "/home/nclarke/.pyenv/versions/3.8.1/envs/playtime/lib/python3.8/site-packages/invoice2data/main.py", line 222, in main
    output_module.write_to_file(output, args.output_name, args.output_date_format)
  File "/home/nclarke/.pyenv/versions/3.8.1/envs/playtime/lib/python3.8/site-packages/invoice2data/output/to_csv.py", line 48, in write_to_file
    writer.writerow(first_row)
UnboundLocalError: local variable 'first_row' referenced before assignment
```

This suggests that it is not matching on the pge.yml template I have created and placed in 

```
ls ~/template
pge.yml*
```

I tried commenting out a few of the keywords It thought might be problematic such as the phone number and urls, but that did not seem to help.

**Comment by m3nu** [comment]
Hi Nickolas, it looks like your template isn't matched. First you should cut back on your keywords. Except for the phone number and website they are probably not necessary. You should only use keywords that are really unique to this one company. (tax IDs are also useful)

Next you should use the debug option to see the actual output of this invoice. If it's an image you may need to use OCR. Passing the option to remove spaces can be useful too.

The error itself is not so relevant here. It just says there is nothing to export as CSV.

**Comment by minalmeg** [comment]
I get something similar and I can't figure out the problem.
`# -*- coding: utf-8 -*-
issuer: **The Company Name which I do not want to disclose**
keywords: 
  - **Company Nam**e
fields:
  invoice number: Invoice no.\n(\d+)
  date: Dated\n(\d{1,2}-\w{3,4}-\d{4})
  cosignee: Cosignee\n(.*)
  buyer: Buyer\(\if other than consignee\)\n(.*)
options:
  remove_whitespace : false
  currency : INR
  languages:
    - en
  date_formats:
    - '%d/%m/%Y'
    `
![InkedInvoice_1_LI](https://user-images.githubusercontent.com/36079785/98463076-c36ba480-21de-11eb-942e-56269bcaeccb.jpg)

PS - I am not trying to extract data from the tables right now. Just the part above the table.

**Comment by rmilecki** [comment]
If you use more recent `invoice2data` you'll see a lot of helpful messages. A list of templates directories, amount of loaded templates, matching results.

As for you case I believe ther problem is invalid file name. YAML templates must be stored in files ending with `.yml`. You somehow got your file named `pge.yml*`. Rename it removing that `*` at the end.
