### ISSUE TITLE
OCR parsing as multiple lines

### ISSUE THREAD

**Issue by temp5374** [invoice-x/invoice2data#279]
Hi there and thank you for the library.  When I am parsing an invoice the debug output shows each field on its own line.  The actual invoice looks like this:

Sales Total :     xxx
Tax Total:         xxx
Total(AUD)      xxx

So basically in the below debug output from GVISION, '24,600.00' and 'Sales Total:' are linked to each other and 2,460.00 and 'Tax Total:' are linked to each other.
```
24,600.00
2,460.00
27,060.00
Sales Total:
< other text >
Tax Total:
< other text >
Total (AUD);
```

Is there a way to handle this?

**Comment by m3nu** [comment]
That's tricky and depends on the OCR. A real-text PDF is usually easiest, if you have the option to use that.

You could still target the above example using some regex, but it will be messy.

**Comment by temp5374** [comment]
Thank you for the quick response!  Okay just checking I wasn't missing anything with the library.  That actually was a real text PDF but I suppose perhaps GVISION just treats it as OCR.

Would you be so kind to point me in the right direction for how I could handle that with regex?  Is it something to do with line breaks or a look back?

**Comment by m3nu** [comment]
Don't use OCR, if you have a real text PDF. The other extractors will do a much better job preserving the layout.

**Comment by temp5374** [comment]
Yes having much better luck with pdftotext for the non image PDFs, thank you.  

However I still do have some image PDFs so what could the regex be in that instance?

**Comment by m3nu** [comment]
> However I still do have some image PDFs so what could the regex be in that instance?

You would have to include the unwanted numbers and line breaks in the regex. A bit messy, but should work.
