### ISSUE TITLE
Amazon pdf

### ISSUE THREAD

**Issue by isviguilsky** [invoice-x/invoice2data#284]
I'm new in invoice2data and I'm learning the project using the examples you posted in the tutorial.

I'm trying to learn how to extract data from invoice detail with no success
I saw the amazon template where contain lines but I would need the amazon.pdf to match the template

are you able to share the amazon pdf related to the template below

issuer: Amazon Web Services, Inc.
keywords:
- Amazon Web Services
fields:
  amount: TOTAL AMOUNT DUE ON.*\$(\d+\.\d+)
  amount_untaxed: TOTAL AMOUNT DUE ON.*\$(\d+\.\d+)
  date: Invoice Date:\s+([a-zA-Z]+ \d+ , \d+)
  invoice_number: Invoice Number:\s+(\d+)
  partner_name: (Amazon Web Services, Inc\.)
options:
  remove_whitespace: false
  currency: HKD
  date_formats:
    - '%d/%m/%Y'
lines:
    start: Detail
    end: \* May include estimated US sales tax
    first_line: ^    (?P<description>\w+.*)\$(?P<price_unit>\d+\.\d+)
    line: (.*)\$(\d+\.\d+)
    last_line: VAT \*\*

Please share another PDF and template in order to learn lines if you do not have the amazon invoice

Thank you, Ivan

**Comment by isviguilsky** [comment]
I realized how to do it. Thak you

**Comment by siddhant-swaroop-dash** [comment]
Im facing the same issue
Suggest some help please
