### ISSUE TITLE
No lines found

### ISSUE THREAD

**Issue by Nishant213** [invoice-x/invoice2data#288]
Although I seem to have used the correct code and format, while running, I get the warnning no lines found - start None end None
Code:
lines:
  - start: Rate\s+Amount\s+Rate\s+Rate\s+Rate\s+Amount$
    end: Total\s+\d+
    line: (?P<HSN_Code>\d+)\s+(?P<Taxable_Amount>\d+.\d+)\s+(?P<Quantity>\d+\s\w+)\s+(?P<IGST_Rate>\d+.\d+)\s+(?P<IGST_Amount>\d+.\d+)\s+(?P<CGST_Rate>\d+.\d+)\s+(?P<CGST_Amount>\d+.\d+)\s+(?P<SGST_Rate>\d+.\d+)\s+(?P<SGST_Amount>\d+.\d+)

Tempelate snippet:
![image](https://user-images.githubusercontent.com/25557155/81512275-05558400-933d-11ea-8253-ef3f76393cb1.png)

Error snippet:
![image](https://user-images.githubusercontent.com/25557155/81543351-948d8680-9393-11ea-8959-5058e0de6060.png)

Can someone please explain what I'm doing wrong here and how I can fix it?
Thank you

**Comment by rmilecki** [comment]
Regex used for `start` didn't match anything in your invoice text. It's hard to say precisely what has happened without text included in your report.

Try dropping `$` from the `start` regex.

**Comment by minalmeg** [comment]
> Although I seem to have used the correct code and format while running, I get the warnning no lines found - start None end None
> Code:
> lines:
> 
> * start: Rate\s+Amount\s+Rate\s+Rate\s+Rate\s+Amount$
>   end: Total\s+\d+
>   line: (?P<HSN_Code>\d+)\s+(?P<Taxable_Amount>\d+.\d+)\s+(?P\d+\s\w+)\s+(?P<IGST_Rate>\d+.\d+)\s+(?P<IGST_Amount>\d+.\d+)\s+(?P<CGST_Rate>\d+.\d+)\s+(?P<CGST_Amount>\d+.\d+)\s+(?P<SGST_Rate>\d+.\d+)\s+(?P<SGST_Amount>\d+.\d+)
> 
> Tempelate snippet:
> ![image](https://user-images.githubusercontent.com/25557155/81512275-05558400-933d-11ea-8253-ef3f76393cb1.png)
> 
> Error snippet:
> ![image](https://user-images.githubusercontent.com/25557155/81543351-948d8680-9393-11ea-8959-5058e0de6060.png)
> 
> Can someone please explain what I'm doing wrong here and how I can fix it?
> Thank you

Did you find any solution for this problem?
