### ISSUE TITLE
remove_whitespace: true is stripping all white spaces

### ISSUE THREAD

**Issue by sudeepjd** [invoice-x/invoice2data#290]
The white_space: true seems to be stripping all the whitespaces

In **invoice_template.py -> prepare_input() method:**

```
# Remove withspace
if self.options['remove_whitespace']:
optimized_str = re.sub(' +', '', extracted_str)  \\\Single Space Here
else:
optimized_str = extracted_str
```

This should be replace with a space so that the regex can split with spaces instead of removing all the spaces... I found this because my templates were not matching when remove_whitespace was true... Adding in the single space worked.

```
# Remove withspace
if self.options['remove_whitespace']:
optimized_str = re.sub(' +', ' ', extracted_str)  \\\Added in the space on this line
else:
optimized_str = extracted_str
```

**Comment by sudeepjd** [comment]
I am not sure if this was intended function or a bug... I can submit a PR to change this, but would like to check if it was intended to remove all spaces or not.

**Comment by m3nu** [comment]
Intended

**Comment by sudeepjd** [comment]
Ok.. Thank you... I will make the changes on my version of the code to make the template match work, without which it is not working, unless I strip white spaces on my template file as well.

**Comment by m3nu** [comment]
You can just turn off whitespace removal.

But I found it's easier to write regex with whitespace removed.
