### ISSUE TITLE
extract data function will not run

### ISSUE THREAD

**Issue by Faizankh8** [invoice-x/invoice2data#292]
Hi, 

The extract_data function will not work for me. Regardless of what i do or which invoice module i use (e.g. tesseract or pdftotext), it does not run the function for me. Please let me know if i'm doing something wrong. 

Steps: 
pip install pdftotext
pip install invoice2data
brew install poppler

>>> from invoice2data import extract_data
>>> from invoice2data.input import pdftotext
>>> import os
>>> os.chdir('//Users//faizankhan//Downloads')
>>> extract_data('test1.pdf', None, pdftotext)
Traceback (most recent call last):
  File "<pyshell#62>", line 1, in <module>
    extract_data('test1.pdf', None, pdftotext)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/invoice2data/main.py", line 82, in extract_data
    extracted_str = input_module.to_text(invoicefile).decode('utf-8')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/invoice2data/input/pdftotext.py", line 30, in to_text
    'pdftotext not installed. Can be downloaded from https://poppler.freedesktop.org/'
OSError: pdftotext not installed. Can be downloaded from https://poppler.freedesktop.org/
>>>

**Comment by logeshstc** [comment]
Hi, Have you find the error?

**Comment by ssj-ali** [comment]
download  pdftotext.exe in your working folder. (you can search pdftotext.exe on google). pdftotext works for digital pdf only.

To use tesseract download Tesseract , Imagemagick and Ghostscript from their sites and then install them.  Finally add them to your environment variables

**Comment by rmilecki** [comment]
Thanks @ssj-ali for your help. It seems indeed that `pdftotext` is not installed in your system. Please install it.
