### ISSUE TITLE
regular expression was changed in the execution time. clueless issue

### ISSUE THREAD

**Issue by rageshS** [invoice-x/invoice2data#293]
Hi All,

I am really disappointed because of the error that I am facing in the invoice2data command prompt. I have a pdf with invoice data. I try to extract the total amount field with Pound currency. I already set my own template YML file in the templates folder. The problem is when I execute the command line for processing `invoice2data --input-reader  pdftotext  mypdf.pdf --template-folder templates --debug` there is some message shows in the output window ( I am using the VS Code editor for the development). and my actual regular expression is shown with some extra charactor. Please see the below details

Regular expression for amount field - `amount: AmountDue*\£(\d+\.\d+)`. I tested this regular expression with an online regular expression website. it works fine. but the output window of VS Code shows a different one 

![image](https://user-images.githubusercontent.com/6523618/85284252-7b0c4e00-b4ac-11ea-8e37-fec78c026745.png)

**Comment by m3nu** [comment]
You probably have an encoding issue somewhere in your workflow. It's not something `invoice2data` does intentional anywhere.

**Comment by rageshS** [comment]
@m3nu Could you please explain, what i am missing for occur the encoding issue. I didn't find any special arguments for mention the encoding standard.

**Comment by m3nu** [comment]
Your template files should be in UTF-8 and you should use Python 3. If that's all fine, you shouldn't see such encoding issues.

**Comment by rageshS** [comment]
Ok, I got your point. But how to mention the encoding format in YML specific. I already checked the python code, it mentions the encoding format in ` main.py` file `extracted_str = input_module.to_text(invoicefile).decode("utf-8")`

**Comment by rageshS** [comment]
I post my solution here for may help someone. If anyone can happen this issue like above `print` your template name and encoding format. 

filename - `\invoice2datamaster\src\invoice2data\extract\loader.py` linenumber - 84

  for path, subdirs, files in os.walk(folder):
        for name in sorted(files):
            if name.endswith(".yml"):
                with open(os.path.join(path, name), "rb") as f:
                    encoding = chardet.detect(f.read())["encoding"]
                    **print('encoding '+encoding)
                    print('name '+name)**
                with codecs.open(
                    os.path.join(path, name), encoding=encoding
                 ) as template_file:
                    tpl = ordered_load(template_file.read())
                   tpl["template_name"] = name
............................................

you can see the template name with encode format. this is for understanding which format had applied in our custom template in invoice2data processing time. 

In my case, I changed the regex like below.

old - `amount: AmountDue*\£(\d+\.\d+)`

new - `  amount: '.*AmountDue*\£(\d+.\d+)'`

when i changed this regex, it's solved my issue.

![image](https://user-images.githubusercontent.com/6523618/85375628-33d99800-b554-11ea-9594-a3fe4cca8717.png)

THANK GOD.......................
