### ISSUE TITLE
Language detection issue

### ISSUE THREAD

**Issue by vdamov** [invoice-x/invoice2data#301]
I can't recognize languages different from English

Tried to detect : Bulgarian, German, Greek

- OS: Windows 10 ( I have invoice2data on macOS High Sierra and it works great which is odd)
- Python 3.8.3
- pip 20.2.3
- conda 4.8.5
- poppler 0.90.1 installed with 'conda install -c conda-forge poppler'
- poppler-data 0.4.9
- pdftotext 0.90.1 installed with 'pip install pdftotext'
- invoice2data installed with 'pip install invoice2data'

I get the same output for each invoice with language different from English:

```
DEBUG:invoice2data.main:START pdftotext result ===========================
DEBUG:invoice2data.main:♀
DEBUG:invoice2data.main:END pdftotext result =============================
DEBUG:invoice2data.main:Testing 113 template files
ERROR:invoice2data.main:No template for invoices/5.pdf

```

**Comment by bosd** [comment]
It has been a while since this issue has been opened.
Please check if it still occurs with the most recent versions of invoice2data.
Closing this one for now.
