### ISSUE TITLE
Cannot access the pdf

### ISSUE THREAD

**Issue by ankitsp02** [invoice-x/invoice2data#303]
I/O Error: Couldn't open file '/invoice/agl_test.pdf': No such file or directory.
No template for /invoice/agl_test.pdf

I get this error, but I have kept this file in this proper directory

**Comment by rmilecki** [comment]
The error message says `No template`, which means not a single template was found that would match your invoice. Matching is done by looking for strings specified in the `keywords`.

For details see https://github.com/invoice-x/invoice2data/blob/master/TUTORIAL.rst
