### ISSUE TITLE
Template variables and the original filename should be allowed as part of --filename-format !

### ISSUE THREAD

**Issue by reikred** [invoice-x/invoice2data#316]
I would like to use something like the following

--copy ./ --filename-format "{date}.{invoice_number}.{issuer}.{orig_filename}"

However, invoice2data does not recognize {issuer} (although it is defined in the template), and {orig_filename} is not supported at all.

Should not --filename-format allow using any variable (attribute) defined in the template file? And should the original filename not also be available to construct the new filename? That would seem logical to me.  If anyone knows any workarounds for what I need, that would be great, too.

Sorry, I'm not much of a python hacker, especially the OO stuff, so I could not figure this out from studying the source code.

**Comment by reikred** [comment]
Note to self (and maybe others): It looks like what I called orig_filename above is called invoicefile in main.py. Nevertheless, one cannot refer to {invoicefile} when constructing --filename-format.

I also see that res['keyword'] is how attribute values are accessed. I tried to put 

issuer=res['issuer'],

into the qppropriate place(s) in main.py, but python complained

KeyError: 'issuer'

**Comment by m3nu** [comment]
You can probably add a pull request to make more variables available for the filename. Should be simple.

**Comment by reikred** [comment]
But I don't know how to do it. I tried the following but get a runtime error as described above:



        if res:
            logger.info(res)
            output.append(res)
            if args.copy:
                filename = args.filename.format(
                    date=res['date'].strftime('%Y-%m-%d'),
                    invoice_number=res['invoice_number'],
                    desc=res['desc'],
                    issuer=res['issuer'], #<----------------------------------added this
                )
                #pdb.set_trace()
                #breakpoint()
                shutil.copyfile(f.name, join(args.copy, filename))
            if args.move:
                filename = args.filename.format(
                    date=res['date'].strftime('%Y-%m-%d'),
                    invoice_number=res['invoice_number'],
                    desc=res['desc'],
                    issuer=res['issuer'], #<----------------------------------added this
                )
                shutil.move(f.name, join(args.move, filename))

**Comment by reikred** [comment]
Please, please, pleaae. I need just a little bit of help here. Give me a hint what went wrong with my attempt.

**Comment by bosd** [comment]
Fixed in #403

**Comment by reikred** [comment]
I have not tested yet, but this sounds awesome and a great enhance,ent.
