### ISSUE TITLE
Problems using gvision

### ISSUE THREAD

**Issue by juanluisrosaramos** [invoice-x/invoice2data#323]
Google has (once again) changed its code to consume its Cloud Vision APIs.  Mostly, my invoices are photos without text to copy.  So I need an OCR and google vision has much better results than tesseract.  So I will update your code I will love to contribute to your software afterwards.

The error that I have is "AttributeError: module 'google.cloud.vision' has no attribute 'types'" so I need to update the code to the last version.

**Comment by m3nu** [comment]
How annoying. Feel free to add a pull request to fix the issue. After that we can make a small release.

**Comment by juanluisrosaramos** [comment]
#324

**Comment by bosd** [comment]
This issue and PR had been open for quite soms while. Propably something we need to work on.


@juanluisrosaramos is your code in the PR still actual?
