### ISSUE TITLE
using tesseract4 option when use as a python library?

### ISSUE THREAD

**Issue by erkin98** [invoice-x/invoice2data#326]
How can i use tesseract option when use inovice2data as a library?

**Comment by RossK1** [comment]
Hey @erkin98,
Haven't tried anything except pdftotext, but you should be able to specify it as the third argument to the extract_data function which is defined as:
`extract_data(invoicefile, templates=None, input_module=pdftotext)`

Docstring shows:
```
input_module : {'pdftotext', 'pdfminer', 'tesseract'}, optional
        library to be used to extract text from given `invoicefile`
```

**Comment by Carlos314159** [comment]
I've tried and it does not work. Anyone managed to use it?

**Comment by bosd** [comment]
I use tesseract as an inputmodule in:
https://github.com/OCA/edi/pull/567

**Comment by bosd** [comment]
@erkin98 @Carlos314159 
New PR in: https://github.com/OCA/edi/pull/722 to fix/restore this functionality.
Would you be so kind to review? :pray:

**Comment by bosd** [comment]
Anyway, recently refactoring has be done on the tesseract input module.
Tesseract 4 is now the default. Languages are automatically detected.

It can now be used on image files.
Currently there is one issue with parsing pdf files.
But hotfix is on it's way in https://github.com/invoice-x/invoice2data/pull/468

Alhough my previous post was in the wrong repo.
It might be usefull for some of you as an code example.

You can see a live test at that pr:
- on gh actions (click on show all checks), --> click on runboat/build **(details)** .
- Click on start (wait a couple of mins, background turns green)
- Click on Live
- Login with user: admin password: admin
- Go to invoicing-->vendors--> Import vendor bills

Closing this one as completed. feel free to reopen.
