### ISSUE TITLE
Manual template selection

### ISSUE THREAD

**Issue by erkin98** [invoice-x/invoice2data#329]
Is it possible to select template manually or with codes?

**Comment by RossK1** [comment]
The read_templates function returns an ordered dict of all of the template yaml files in a given folder. This ordered dict is then passed to the extract_data function which searches each template in turn for matching keywords.
If you must force a specific template, you might try have a very general keyword that is guaranteed to match and then keep that template in a separate folder. You could then do something like:
```
if filename == "my_invoice.pdf":
    template_folder = "/templates/specific_template/"
else:
    template_folder = "/templates/general_templates/"
templates = read_templates(template_folder)
result = extract_data(filename, templates=templates)
```

**Comment by reikred** [comment]
@RossK1 Where is the code above supposed to go?

**Comment by RossK1** [comment]
@reikred , this would only work if you're running it from a python script. In that script, you could loop through the invoice files to process and, when one matching the specified name is found, it selects the given template folder.

**Comment by rmilecki** [comment]
You can use:
```
invoice2data --exclude-built-in-templates --template-folder /path/to/your/folder/with/one/template/only/
```
