### ISSUE TITLE
Integrate with online OCR + Online GUI using Konfuzio.com ?

### ISSUE THREAD

**Issue by atraining** [invoice-x/invoice2data#338]
Hi Manu / @m3nu ,

I accidentally found your project. The straightforward approach to using templates is great. However, I assume they are hard to maintain. This was at least our learning. 

Our Python SDK is in private Beta which allows you to connect to different online OCRs and a web-based PDF labeling tool. We could even allow you to access the results of our Regex Generator which allows you to create optimized Regex based on annotations in the documents.

There is a free tier, I assume this might be sufficient for many users.

Br,

Chris

Disclaimer: I am one of the Co-Founders of [Konfuzio](https://konfuzio.com)

**Comment by m3nu** [comment]
All the best for your startup, Chris!
