### ISSUE TITLE
to_csv error

### ISSUE THREAD

**Issue by bagcivan** [invoice-x/invoice2data#342]
I can see the invoice, but I get an error when I want to export as a csv file. 
where am I doing wrong?

code
```
from invoice2data import extract_data
from invoice2data.extract.loader import read_templates
from invoice2data import output 


templates = read_templates('Template/')

result = extract_data('invoice/QualityHosting.pdf', templates=templates)

output.to_csv.write_to_file(result,"invoice.csv")
```

dict
`{'issuer': 'QualityHosting AG', 'amount': 34.73, 'amount_untaxed': 34.73, 'date': datetime.datetime(2014, 5, 7, 0, 0), 'invoice_number': '30064443', 'vat': 'DE 232 446 240', 'currency': 'EUR', 'lines': [{'pos': '1', 'qty': 1.0, 'desc': 'Small Business StandardExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_strukan\n01.05.14-31.05.14', 'price': 3.89}, {'pos': '2', 'qty': 1.0, 'desc': 'Small Business QualityExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_schneider\n01.05.14-31.05.14', 'price': 5.39}, {'pos': '3', 'qty': 1.0, 'desc': 'Small Business QualityExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_minar\n01.05.14-31.05.14', 'price': 5.39}, {'pos': '4', 'qty': 1.0, 'desc': 'Small Business QualityExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_mayr\n01.05.14-31.05.14', 'price': 5.39}, {'pos': '5', 'qty': 1.0, 'desc': 'Small Business QualityExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_jenewein\n01.05.14-31.05.14', 'price': 5.39}, {'pos': '6', 'qty': 1.0, 'desc': 'Small Business QualityExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_jauernik\n01.05.14-31.05.14\nQualityHosting AG - Uferweg 40-42 - D-63571 Gelnhausen\niViveLabs Ltd.\n93B Sai Yu Chung\nYuen Long, N.T.\nHong Kong\nPos.            Menge      Beschreibung                                                            Rabatt %     VK-Preis     Zeilenbetrag\nOhne      Ohne MwSt.\nMwSt.', 'price': 5.39}, {'pos': '7', 'qty': 1.0, 'desc': 'Small Business StandardExchange 2010\nGrundgebühr pro Einheit\nDienst: OUDJQ_office\n01.05.14-31.05.14\n', 'price': 3.89}], 'desc': 'Invoice from QualityHosting AG'}`

error
```
File "C:\Users\tevfi\anaconda3\lib\site-packages\invoice2data\output\to_csv.py", line 45, in write_to_file
    for k, v in line.items():

AttributeError: 'str' object has no attribute 'items
```

**Comment by georgemagnuson** [comment]
Any resolution to this?

I am getting the same error for when using as a library and json, csv and xml output. When the dictionary result is passed to ...write_to_file it comes back with an 
Exception has occurred: AttributeError 'str' object has no attribute 'items' 

No problems when invoked as invoice2data on the command line.

**Comment by daneucza** [comment]
Hey, try doing this:
result = [extract_data('invoice/QualityHosting.pdf', templates=templates)]

output.to_csv.write_to_file(result,"invoice.csv")

**Comment by rmilecki** [comment]
Every output module expects **array of extracted data** (array of dictionaries) as argument.

See how `main()` handles it in the `main.py`:
```
    output = []
    for f in args.input_files:
        res = extract_data(f.name, templates=templates, input_module=input_module)
        if res:
            logger.info(res)
            output.append(res)
            (...)
        f.close()
```

So you need to create array as suggested by @daneucza or you can try more open coded version like:
```
output = []
result = extract_data('invoice/QualityHosting.pdf', templates=templates)
output.append(result)
output.to_csv.write_to_file(result,"invoice.csv")
```
