### ISSUE TITLE
Lines Feature: Capturing multiple positions AND the respective order number

### ISSUE THREAD

**Issue by olojonas778** [invoice-x/invoice2data#346]
<img width="390" alt="Screenshot 2021-05-31 at 18 13 50" src="https://user-images.githubusercontent.com/13274603/120219729-f7bab700-c23b-11eb-9c16-3ac334079913.png">
Hi! I am running into an issue with parsing the order number for a set of positions  using the lines feature.

As you can see from the picture, I have invoices containing n orders with m positions each. I have no issue parsing out the lines. However, additionally parsing out the respective order number for each subset of positions I don't know how to do. The way I currently understand the 'first_line', 'lines' and 'last_line' abilities is that it allows to read from up to three lines for any position of an invoice. Here, I only have one line per position, but multiple positions make up one order and capturing that reference is key for me. Is there currently a way to capture the order number corresponding to each sub-set of positions with the lines feature as is? Could this be something that can be added at some point otherwise?

Thanks so much!
Jonas

**Comment by bosd** [comment]
Hi Jonas,

Can you give an example of your current output and the desired output??

**Comment by rmilecki** [comment]
What I believe is be the best option for you is to
1. Write a small Python script
2. Use `invoice2data` as library
3. Extract data and process it in your small app

Alternative you could also use CLI and then modify extracted JSON/XML to match your needs.

I believe you should write template to extract data to following format:
```
[
    {
        "order_number": "AB-12345"
    },
    {
        "position": 1,
        "qty": 5,
        "unit_price": 5.0,
        "total_price": 25.0,
    },
    {
        "position": 2,
        "qty": 1,
        "unit_price": 10.0,
        "total_price": 10.0,
    },
    {
        "position": 3,
        "qty": 4,
        "unit_price": 8.0,
        "total_price": 32.0,
    },
    {
        "order_number": "AB-11126"
    },
    {
        "position": 4,
        "qty": 5,
        "unit_price": 5.0,
        "total_price": 25.0,
    },
    (...)
]
```
and then process it as suggested above.

**Comment by rmilecki** [comment]
Support for multiple (different) `line` patterns was added in the https://github.com/invoice-x/invoice2data/pull/417 - that should help.
