### ISSUE TITLE
I have installed invoice2data and pdftotext but i'm facing this error whenever i write "invoice2data invoice2.pdf" why?

### ISSUE THREAD

**Issue by lakshay2k** [invoice-x/invoice2data#348]
I even tried on the test pdf given on GitHub profile then also it is saying no template found

**Comment by lakshay2k** [comment]
I have started extracting the invoice data using the regex and was successful enough to extract various attributes. feel free to contact if you wish to do the same, I will assist you

**Comment by datvtzodinet** [comment]
@lakshay2k  can you assist me with how to run this command. I face the same problem as you. Many thanks.
