### ISSUE TITLE
Need an example with a greek invoice

### ISSUE THREAD

**Issue by johnrogerpap** [invoice-x/invoice2data#363]
Hey can someone please give me an example of a yml template for a greek invoice. Is greek language supported? I am trying to parse the data from Greek and i cant. Ideally i would like the yml template for the attached pdf file. Thank you in advance
[tda340.pdf](https://github.com/invoice-x/invoice2data/files/7626610/tda340.pdf
[gr.PALIN.TXT](https://github.com/invoice-x/invoice2data/files/7626783/gr.PALIN.TXT)
)

**Comment by rmilecki** [comment]
Please attach YAML you tried so there is some starting point to help you debugging it :)

**Comment by johnrogerpap** [comment]
I updated the question. The yml file is the PALIN.txt. Thank you so much

**Comment by rmilecki** [comment]
I renamed `gr.PALIN.TXT` to `gr.PALIN.yml` and put it in my `tpl` directory. It looks OK:
```
$ invoice2data --exclude-built-in-templates --template-folder tpl tda340.pdf 
Loaded 1 templates from /home/rmilecki/tpl
Using gr.PALIN.yml template
no table body found - start None, end None
{'issuer': 'PALIN', 'amount': [], 'date': [], 'invoice_number': [], 'vat': '045234832', 'currency': 'EUR', 'desc': 'Invoice from PALIN'}
```
Now you need to obviously write RegEx-es for invoice fields.

The problem I see will be formatting of data in that invoice, see:
```
                                  ΕΙΔΟΣ ΠΑΡΑΣΤΑΤΙΚΟΥ                                               ΣΕΙΡΑ           ΑΡΙΘΜΟΣ                  ΗΜΕΡΟΜΗΝΙΑ                 ΩΠΠ/ΩΡΑ ΑΠ
                         TIMOΛOΓIO - ΔEΛTIO AΠOΣTOΛHΣ                                              TDA               000340                   10/06/21                     1638
```
There is no easy way of parsing that.

You can try mult-line RegEx but it will be tricky to get the right field. See something like:
```
date: ΗΜΕΡΟΜΗΝΙΑ.*\n.*(\d{2}/\d{2}/\d{2})
```
(that also causes `ValueError: Unknown language(s): 'gr'` for some reason - I had to remove `gr` language to make it work).

**Comment by johnrogerpap** [comment]
@rmilecki Thank you again for all the effort. Can you attach the changed yml file? Did you change the language from gr to something else? Did you manage to parse the date?

**Comment by rmilecki** [comment]
Check https://dateparser.readthedocs.io/en/latest/supported_locales.html - there is no `gr`. I guess Greek language is not supported by `dateparser`. Don't worry though. Just remove that and it still should work fine.

```
$ cat tpl/gr.PALIN.yml 
# -*- coding: utf-8 -*-
issuer: PALIN
fields:
  amount: ΠΛΗΡΩΤΕΟ\s+(\d+,\d{2})
  date: ΗΜΕΡΟΜΗΝΙΑ.*\n.*(\d{2}/\d{2}/\d{2})
  invoice_number: Invoice\s+Number\s?:\s+(\w+)
  static_vat: 045234832
tables:
  - start: VAT Basis\s+VAT Amount\s+VAT Rate
    end: 'Pour plus'
    body: '\s+(?P<amount_untaxed>\d*,\d*)\s+(?P<amount_tax>\d*,\d*)\s+(?P<vat_rate>\d*,\d*)\s+%'
keywords:
  - 23730 24623,
  - fempharm@yahoo.com
  - ΠΑΛΙΝ
options:
  currency: EUR
  date_formats:
    - '%d.%m.%Y'
  decimal_separator: ','
```
```
$ invoice2data --exclude-built-in-templates --template-folder tpl tda340.pdf 
Loaded 1 templates from /home/rmilecki/praca/healthy/ocr/tpl
Using gr.PALIN.yml template
/home/rmilecki/.local/lib/python3.6/site-packages/dateparser/date_parser.py:35: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  date_obj = stz.localize(date_obj)
no table body found - start None, end None
{'issuer': 'PALIN', 'amount': 534.42, 'date': datetime.datetime(2021, 10, 6, 0, 0), 'invoice_number': [], 'vat': '045234832', 'currency': 'EUR', 'desc': 'Invoice from PALIN'}
```

**Comment by johnrogerpap** [comment]
Hey thanks it is working for total amount and date. Now do i have to do the same for the product lines? how can i get those? Thank you so much for helping

**Comment by rmilecki** [comment]
You need to learn how to write RegEx-es and put them in your `.yml` file. This is the basic `invoice2data` assumption. It's based on RegEx-es and you have to understand them to write your own templates.
