### ISSUE TITLE
Does it work for scanned PDF's ?

### ISSUE THREAD

**Issue by pavankalyan066** [invoice-x/invoice2data#366]
Unable to match all required fields. The required fields are: ['date', 'amount', 'invoice_number', 'issuer']. Output contains the following fields: ['date', 'currency', 'issuer'].

My template:
`[InvoiceTemplate([('issuer', 'Honeywell Int. SDN. BHD'),
                  ('keywords', ['Honeywell']),
                  ('fields',
                   OrderedDict([('date',
                                 'DATE OF TASK\\n(\\d{2}-\\w{A-Z}\\d{2})')])),
                  ('options', OrderedDict([('remove_whitespace', True)])),
                  ('template_name', 'sing.gb.airline.yml'),
                  ('exclude_keywords', [])])]`

Could Anyone Please Help to fix my issue! Thank you.

**Comment by bosd** [comment]
can you share your input file and template?
