### ISSUE TITLE
Can't obtain matching regex

### ISSUE THREAD

**Issue by KJeulink** [invoice-x/invoice2data#368]
Hi all! I am running into a problem. One of my invoices has a part as shown below. I use the following regex to indentify and extract the amount (Totaalbedrag): 
  amount: Totaalbedrag\s+€\s+([+-]?[0-9]{1,3}(?:\.?[0-9]{3})*(?:,[0-9]{2})?)

An online regex tester recognizes the line, however somehow invoice2data can't find this line. I am getting stuck here. Has somebody any idea what is going wrong? Thanks for the help!

`<pre>

Pensioenpremie
Verrekeningen juli 2019 t/m april 2021                                                   €            -3.374,27

Totaalbedrag                                                                             €            -3.374,27

</pre>`

**Comment by rmilecki** [comment]
Run `invoice2data` with a `--debug` option and provide an output here.

**Comment by KJeulink** [comment]
Thanks for the quick response, see below the output

`
<pre>DEBUG:invoice2data.main:START pdftotext result ===========================
DEBUG:invoice2data.main:                                                                        Werkgeversdesk
                                                                        (123) 123 12 12
                                                                        maandag t/m vrijdag
                                                                        8.00 tot 17.00 uur
                                                                        Organisatienummer
                                                                        123456
Abcadfspdfadf                                                           Factuurnummer

Ab A AadkfAjkffd 1234                                                   AB12345678
1234 AB APELDOORN                                                       Factuurdatum
                                                                        30 april 2021




                                                                        Factuur
                                                                        Pensioenregeling




Pensioenpremie
Verrekeningen juli 2019 t/m april 2021                                                   €            -1.123,12


Totaalbedrag                                                                             €            -1.123,12




Een creditbedrag brengen wij in mindering op openstaande facturen waarvan de vervaldatum verstreken is.
Als er geen openstaande facturen zijn en/of verrekening niet mogelijk is, betalen wij het creditbedrag binnen
30 dagen aan u terug.

Bekijk de details van deze factuur op blab.nl/mijnorganisatie.




Pensioenfonds Blaa bl Blaaaaa                                      Tel:                (123) 123 12 12
Noordweg Noord 123, Zeist                                          Contact:            www.blab.nl/info
Postbus 123, 1234 AC ZEIST                                         Kvk nummer:         12345678
www.pfzw.nl


DEBUG:invoice2data.main:END pdftotext result =============================
DEBUG:invoice2data.main:Testing 147 template files
DEBUG:invoice2data.extract.invoice_template:Template: pensioenfonds-Blaa-en-Blaaaaa.yml. Keywords matched. No exclude keywords found.
DEBUG:invoice2data.extract.invoice_template:START optimized_str ========================
DEBUG:invoice2data.extract.invoice_template:                                                                        Werkgeversdesk
                                                                        (123) 123 12 12
                                                                        maandag t/m vrijdag
                                                                        8.00 tot 17.00 uur
                                                                        Organisatienummer
                                                                        123456
FijnThuisBlaa                                                           Factuurnummer

Ab A AadkfAjkffd 1234                                                   AB12345678
1234 AB APELDOORN                                                       Factuurdatum
                                                                        30 april 2021




                                                                        Factuur
                                                                        Pensioenregeling




Pensioenpremie
Verrekeningen juli 2019 t/m april 2021                                                   €            -1.123,12


Totaalbedrag                                                                             €            -1.123,12




Een creditbedrag brengen wij in mindering op openstaande facturen waarvan de vervaldatum verstreken is.
Als er geen openstaande facturen zijn en/of verrekening niet mogelijk is, betalen wij het creditbedrag binnen
30 dagen aan u terug.

Bekijk de details van deze factuur op pfzw.nl/mijnorganisatie.




Pensioenfonds Blaa bl Blaaaaa                                      Tel:                (123) 123 12 12
Noordweg Noord 123, Zeist                                          Contact:            www.pfzw.nl/info
Postbus 123, 1234 AB ZEIST                                         Kvk nummer:         12345678
www.pfzw.nl


DEBUG:invoice2data.extract.invoice_template:END optimized_str ==========================
DEBUG:invoice2data.extract.invoice_template:Date parsing: languages=[&apos;nl&apos;] date_formats=[&apos;%d-%m-%Y&apos;]
DEBUG:invoice2data.extract.invoice_template:Float parsing: decimal separator=,
DEBUG:invoice2data.extract.invoice_template:keywords=[&apos;Organisatienummer\\s+123456&apos;]
DEBUG:invoice2data.extract.invoice_template:{&apos;remove_whitespace&apos;: False, &apos;remove_accents&apos;: False, &apos;lowercase&apos;: False, &apos;currency&apos;: &apos;EUR&apos;, &apos;date_formats&apos;: [&apos;%d-%m-%Y&apos;], &apos;languages&apos;: [&apos;nl&apos;], &apos;decimal_separator&apos;: &apos;,&apos;, &apos;replace&apos;: []}
DEBUG:invoice2data.extract.invoice_template:field=amount | regexp=Totaalbedragâ‚¬([+-]?[0-9]{1,3}(?:\.?[0-9]{3})*(?:,[0-9]{2})?)
DEBUG:invoice2data.extract.invoice_template:field=date | regexp=Factuurdatum\s+(\d{1,2}-\d{1,2}-\d{4})
DEBUG:invoice2data.extract.invoice_template:field=invoice_number | regexp=Factuurnummer\s+(.+)
DEBUG:invoice2data.extract.invoice_template:{&apos;issuer&apos;: &apos;Pensioenfonds Blaa &amp; Blaaaaa&apos;, &apos;amount&apos;: [], &apos;date&apos;: [], &apos;invoice_number&apos;: &apos;Ab A AadkfAjkffd 1234                                                   AB12345678&apos;, &apos;currency&apos;: &apos;EUR&apos;, &apos;desc&apos;: &apos;Invoice from Pensioenfonds Blaa &amp; Blaaaaa&apos;}
INFO:invoice2data.main:{&apos;issuer&apos;: &apos;Pensioenfonds Blaa &amp; Blaaaaa&apos;, &apos;amount&apos;: [], &apos;date&apos;: [], &apos;invoice_number&apos;: &apos;Ab A AadkfAjkffd 1234                                                   AB12345678&apos;, &apos;currency&apos;: &apos;EUR&apos;, &apos;desc&apos;: &apos;Invoice from Pensioenfonds Blaa &amp; Blaaaaa&apos;}
</pre>

`

**Comment by rmilecki** [comment]
> `DEBUG:invoice2data.extract.invoice_template:field=amount | regexp=Totaalbedragâ‚¬([+-]?[0-9]{1,3}(?:\.?[0-9]{3})*(?:,[0-9]{2})?)`

`€` from your `.yml` looks malformed, it seems `invoice2data` used wrong encoding while opening your `.yml`.

As a quick check: please replace `€` with `.` to verify my idea.

`invoice2data` uses `chardet` to detect `.yml` file encoding. It seems to fail in this case. I'm wondering if we need that `chardet` at all. Does `invoice2data` respect `# -*- coding: utf-8 -*-` headers from `.yml` files at all?

**Comment by KJeulink** [comment]
Replacing the euro sign with . worked! Thank you very much!

**Comment by rmilecki** [comment]
Solved by 6ab31047386a ("Treat all YAML templates files as UTF-8 encoded")
