### ISSUE TITLE
Please enable option to specifiy legacy parameter

### ISSUE THREAD

**Issue by Marcel257** [invoice-x/invoice2data#369]
Dear development team,

In the invoice_template.py the [legacy parameter is hard-coded set to true](https://github.com/invoice-x/invoice2data/blob/36863386692a2393d561cdaa1e3a5e4938c34935/src/invoice2data/extract/invoice_template.py#L204).

This leads to [using a set for eliminating duplicates](https://github.com/invoice-x/invoice2data/blob/36863386692a2393d561cdaa1e3a5e4938c34935/src/invoice2data/extract/parsers/regex.py#L57) in the regex.py. This way, the original order of the matches is not guaranteed.

In my use case, I need to maintain the order of matches.
Could you please enable an option to set the parameter (either in the template or via parameter in the extract method in invoice_template.py) to maintain order of matches?

Greetings
Marcel

**Comment by rmilecki** [comment]
I see no point in adding more features to the legacy syntax. Just use new syntax in your template file.

**Comment by Marcel257** [comment]
@rmilecki Could you please explain how to do that?
The legac parameter is set to true in the method _extract_ in the invoice_template.py.

What module/method do we need to call to extract without legacy mode in the regex.py?

**Comment by Marcel257** [comment]
@rmilecki I see. I need to define an explicit regex parser and I used the legacy syntax. Thanks for your help, I appreciate it.
