### ISSUE TITLE
Local unit test fails: FileNotFoundError

### ISSUE THREAD

**Issue by bosd** [invoice-x/invoice2data#381]
Local unit test fails: FileNotFoundError

Caused by relative path in:
https://github.com/invoice-x/invoice2data/blob/36863386692a2393d561cdaa1e3a5e4938c34935/tests/test_cli.py#L162

steps to reproduce:
1. go to invoice2data/tests
2. `$ python test_cli.py`

**Comment by rmilecki** [comment]
Does it happen if you run tests using
```
python -m tests.test_cli
```
? 

That seems to be prefered way of running tests that works without your changes from the https://github.com/invoice-x/invoice2data/pull/380 :
- [Relative imports in Python 3](https://stackoverflow.com/questions/16981921/relative-imports-in-python-3)
- [Relative imports for the billionth time](https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time)

I don't get that `FileNotFoundError` when using `python -m tests.test_cli`.

**Comment by bosd** [comment]
> I don't get that `FileNotFoundError` when using `python -m tests.test_cli`.

Yes, using that command it is working :+1:
