### ISSUE TITLE
No template folder in the project folder.

### ISSUE THREAD

**Issue by SkiBumUtah** [invoice-x/invoice2data#425]
The TUTORIAL.md files says, 
"Existing templates can be found in the project folder or the installed package under /invoice2data/templates/." 
I think I found the folder in src/invoice2data/extract/templates. Seems like the Tutorial.md should be updated and/or provide a link. 

If possible, it would be a lot better if the template folder was accessible from the main file. I assume you have beginners like me trying to figure this out. I didn't know what src was and had no reason to think that the template folder would be buried in it three folders deep.

**Comment by SkiBumUtah** [comment]
I found the folder. Its in src/invoice2data/extract. Seems like the Tutorial.md should be updated to add src/.

**Comment by bosd** [comment]
implemented in 426
