### ISSUE TITLE
unidecode dependency is using GPL-2.0 license

### ISSUE THREAD

**Issue by markokoleznik-cs** [invoice-x/invoice2data#435]
Hello devs,
While `invoice2data` itself is licensed as a MIT, the dependant library `unidecode` (https://github.com/avian2/unidecode) uses GPL-2.0 license.
Because of this, `invoice2data` cannot be used within our project.

Do you have any remediation path available? If not, is there a plan to replace a library with the one with MIT license, if there is any? This is currently a blocker for us.

Attached see the screenshot of the Snyk report:
<img width="906" alt="image" src="https://user-images.githubusercontent.com/67679686/201322995-a250c85c-45cd-48af-af9d-eb0d5cc25585.png">

**Comment by bosd** [comment]
What would you propose to use as an alternative library?

**Comment by markokoleznik-cs** [comment]
From what I see in the repo, here is the only place that `unidecode` library is actually used: https://github.com/invoice-x/invoice2data/blob/4b2e00c304f32f082f5e416e29339054d238d095/src/invoice2data/extract/invoice_template.py#L82

I'm guessing here, but it seems that this could do the trick: https://stackoverflow.com/a/1207479
Not sure about 100% compatibility but IMO it's worth checking it out.

**Comment by bosd** [comment]
> I'm guessing here, but it seems that this could do the trick: https://stackoverflow.com/a/1207479
> Not sure about 100% compatibility but IMO it's worth checking it out.

I don't have a strong opinion on this. (my Native language is mainly in ascii chars).
So that proposal would be fine by me.

I also found that some people are exchanging the library for this:
https://pypi.org/project/text-unidecode/

@rmilecki What is your insight on this?

**Comment by markokoleznik-cs** [comment]
I have tried to open a PR, but got rejected with permission denied.
I've tried that and it seems to work.
Running `pytest` produces the same output as before the changes.
Dumping output of `git diff master` here:

```
diff --git a/setup.cfg b/setup.cfg
index 7ab4c97..d04d888 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -38,7 +38,6 @@ install_requires =
   pillow
   pyyaml
   dateparser
-  unidecode

 [options.extras_require]
 test = pytest; pytest-cov; flake8; pdfminer.six; pdfplumber; tox
diff --git a/src/invoice2data/extract/invoice_template.py b/src/invoice2data/extract/invoice_template.py
index 77ab1ca..4ca7245 100644
--- a/src/invoice2data/extract/invoice_template.py
+++ b/src/invoice2data/extract/invoice_template.py
@@ -6,8 +6,8 @@ Templates are initially read from .yml files and then kept as class.

 import re
 import dateparser
-from unidecode import unidecode
 import logging
+import unicodedata
 from collections import OrderedDict
 from . import parsers
 from .plugins import lines, tables
@@ -79,7 +79,7 @@ class InvoiceTemplate(OrderedDict):

         # Remove accents
         if self.options["remove_accents"]:
-            optimized_str = unidecode(optimized_str)
+            optimized_str = unicodedata.normalize('NFKC', optimized_str).encode('ascii', 'ignore').decode('ascii')

         # convert to lower case
         if self.options["lowercase"]:
```

**Comment by bosd** [comment]
Since the PR has been merged. An new release is on it's way, this one cone be closed now.
Thanks @markokoleznik-cs
