### ISSUE TITLE
remove_accents option does not work properly anymore

### ISSUE THREAD

**Issue by alainv62** [invoice-x/invoice2data#444]
Since the removal of the unidecode library and its replacement with the unicodedata module in commit https://github.com/invoice-x/invoice2data/commit/4d517d131fdaa568b4282f2f0a12abef98751075, the remove_accents option does not work properly anymore.
Eg: in French, 'référence' is replaced with 'rfrence'.
It seems that the normal form KC is here responsible as the normal form KD works fine with this example ('référence' is properly replaced with 'reference').

**Comment by esmeraldas63** [comment]
Have encountered same issues with Lithuanian and Latvian letters too

**Comment by bosd** [comment]
We need to fix this! Currently im travelling. So not much time to attend to this.
Does anyone have a suggestion for an alternative implementation or library?

**Comment by alainv62** [comment]
Why not just revert to the former solution `optimized_str = unidecode(optimized_str)` which was working fine?

**Comment by bosd** [comment]
> Why not just revert to the former solution ?

Because of the mentioned license issue.

There are some good alternatives. Like built-ins or alternative libraries ( adding extra dependencies is not preferred).

**Comment by alainv62** [comment]
What about using the normal form KD ?

**Comment by rmilecki** [comment]
> Why not just revert to the former solution `optimized_str = unidecode(optimized_str)` which was working fine?

See description in pull request that introduced that change: https://github.com/invoice-x/invoice2data/pull/436

And for the orginal report: https://github.com/invoice-x/invoice2data/issues/435

**Comment by bosd** [comment]
> What about using the normal form KD ?

Yes, that seems to fix it..
small test:
```
>>> str1="référence"
>>> unicodedata.normalize('NFKD', str1).encode('ascii', 'ignore').decode('ascii')
'reference'
```


```
>>> str2="ä"
>>> unicodedata.normalize('NFKD', str2).encode('ascii', 'ignore').decode('ascii')
'a'
```

**Comment by bosd** [comment]
It is probably an good idea to add a test for the remove accents function.
Is there an example invoice to add to the tests?
