### ISSUE TITLE
Multiline Column merging next row 

### ISSUE THREAD

**Issue by zanpk** [invoice-x/invoice2data#455]
Recently started using this amazing library. When i try to parse multiline column unfortunately its also merging next row with data. It would be very helpful if you can help me on this.
**Issue: description next line is merged with next row (bold in output mentioned below)**
Kindly visit this[ link for invoice pdf.](https://docdro.id/AxXNXXZ)
```
templete:
issuer: XYZ

fields:
amount:
parser: regex
regex: Balance Due.+
type: float
date: date.+
invoice_number: inv.+

items:
employee_milege:
parser: lines
start: 'Quantity\s+Item Code\s+Description\s+Price Each\s+Amount'
end: '\s+Tax\s+(\d+.\d+%)'
first_line: (?P(.+))\s+(?P<item_code>(TRAVEL))\s+(?P.+)\s+(?P(\d+(?:.\d+)?))\s+(?P(\d+(?:.\d+)?))
line: (?P.+)

keywords:

xyzcompany
options:
currency: USD
decimal_separator: "."
```
Output:
```
'items': [
{'quantity': '745', 'item_code': 'TRAVEL', 'description': 'TRAVEL: 2-way (round-trip) Air Fare from New York to New Jersey in\nXXXX. - for Steve Smith.\n**3 Custom This is next line here. 50.00
150.00\n3 Custom Second next line here
50.00 150.00\n50.00 100.00**', 'price': '0.58', 'amount': '595.08'}], 'currency': 'USD', 'desc': 'Invoice from XYZ'}
```

**Comment by rmilecki** [comment]
@zanpk: `first_line` is meant to match first line of **every** invoice item. So you need to make sure your `first_line` matches first lines of all **three** items.

Then `line` is meant to handle **extra** item lines in case there is more than one. It applies to your **first** item case which has `XXXX. - for Steve Smith.` in the second line.

So please rewrite your `first_line` regex. Don't make it `(TRAVEL)` specific as that matches only the first invoice item. The correct regex has to match all three:

```
      745 TRAVEL           TRAVEL: 2-way (round-trip) Air Fare from New York to New Jersey in                         0.58               595.08
```
```
           3 Custom        This is next line here.                                                                 50.00                 150.00
```
```
           3 Custom        Second next line here                                                                   50.00                 150.00
```

**Comment by zanpk** [comment]
thanks again for your response, got it but actually dont want to get all rows that why I filtered with TRAVEL. 
So you are saying that I should get all rows first without any filter then using python string regex filter them ?

**Comment by bosd** [comment]
This sounds like a job for Camelot plugin..
Its still a WIP for me..
