### ISSUE TITLE
Could not parse table data when some column names are missing

### ISSUE THREAD

**Issue by zanpk** [invoice-x/invoice2data#458]
Hello,
I would like to thanks @rmilecki for your responses most of my previous issues resolved now. 
Now i want to parse data from invoice in which some column names are missing i have tried but unfortunately data on column with no names merged with the previous column data. 
You can view the invoice by[ visiting this link](https://docdro.id/r9jZvyg).

Desired Output:
Serial Number, Product Description, QuantityxPrice, Amount

Actual Output:
{'sr': '1.   Product 1 2 x 10', 'product': '', 'quantity': '', 'amount': '20'},
Thanks

template code:
invoice_data:
    parser: lines
    start: '\s+Product\s+\s+Amount'
    end: '\s+Total.+'
    first_line: (?P<sr>.+)\s+(?P<product>.+)\s+(?P<quantity>.+)\s+(?P<amount>.+)
    line: (?P<product>.+)

**Comment by rmilecki** [comment]
Stop creating a new issue for every support request you have. That will cause a mess in project issues. What you are reporting so far are not even actual issues.
