### ISSUE TITLE
Google Summer of Code 2023

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoice2data#462]
Since I see a lot of activity here recently, I wanted to check if you guys are interested in applying for [Google Summer of Code](https://developers.google.com/open-source/gsoc). This would be as sub-org via Debian or Python.

This could help to get some issues and tasks done and support those 2 orgs (they get a stipend for each mentor). This project already joined GSoC in 2018 via Debian. I can be a backup mentor, but will focus on Borg and Vorta this year. We would need 2 mentors who are active on the project. You would choose and assign tasks and track the progress. E.g. with GH issues or the Kanban feature.

Pinging @rmilecki, @bosd @alexis-via

**Comment by rmilecki** [comment]
I'm sorry but my free time is really limited and I find time only occasionally to work on this project (every few months).

I may be able to find some time for reviewing but no promises.

**Comment by bosd** [comment]
I'm interested, but the deadline seems way to close for me.
To draft the ideas and tasks for this project.

**Comment by m3nu** [comment]
If you apply via PSF, it's pretty quick. Feel free to copy from the page I put together for Vorta just now.

https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas

For tasks, just pick the tasks you find important and elaborate a bit.

**Comment by bosd** [comment]
This one can be closed now, we did not make the application deadline
