### ISSUE TITLE
Failed to extract using invoice2data.input.pdftotext

### ISSUE THREAD

**Issue by beeshaker** [invoice-x/invoice2data#473]
Hi am getting a weird error:
Failed to extract text from Invoice\Amazon.pdf using invoice2data.input.pdftotext
False

Trying the basic use case here, ive ensured the invoice name and template name match, my current code:

```
from invoice2data import extract_data
from invoice2data.extract.loader import read_templates


templates = read_templates('Template\\')
print(templates)

result = extract_data('Invoice\\Amazon.pdf', templates=templates)
print(result)
```

**Comment by rmilecki** [comment]
What happens when:

1. You run `pdftotext Invoice\Amazon.pdf` manually - can you see invoice's text?
2. You run `invoice2data --debug --template-folder Template Invoice\Amazon.pdf` manually - does your invoice get parsed?

**Comment by beeshaker** [comment]
1. when i run `pdftotext Invoice\Amazon.pdf` nothing is output, i get no fail, error or any output 
2. When i run `invoice2data --debug --template-folder Template Invoice\Amazon.pdf`  i get the same error `ERROR:invoice2data.main:Failed to extract text from Invoice\Amazon.pdf using invoice2data.input.pdftotext`

**Comment by rmilecki** [comment]
It most likely means your `Amazon.pdf` doesn't contain and text in a text form. It may be PDF with just an image (either: generated or scanned). For such invoices you'll need to use OCR. You may try your luck with `tesseract` or `gvision`.

It's not a bug in such case.

**Comment by beeshaker** [comment]
Hi the Amazon.pdf is the same invoice i found under the github repo https://raw.githubusercontent.com/invoice-x/invoice2data/master/tests/compare/AmazonWebServices.pdf

**Comment by rmilecki** [comment]
> when i run `pdftotext Invoice\Amazon.pdf` nothing is output, i get no fail, error or any output

Ah, I forogt that `pdftotext` creates text file by default. Is there `Invoice\Amazon.txt` (mind the `.txt`) with invoice text content?

**Comment by rmilecki** [comment]
Or just try running `pdftotext Invoice\Amazon.pdf -` and let us know if you can see invoice's text

**Comment by beeshaker** [comment]
Hi still nothing

**Comment by rmilecki** [comment]
There is some problem with your local `pdftotext`. If it doesn't work properly, `invoice2data` simply doesn't have any text to work on. You need to fix your `pdftotext` tool.

**Comment by beeshaker** [comment]
Thank i think the case is the later any suggestions on how to ensure pdftotext works ps im on windows

**Comment by rmilecki** [comment]
Sorry, but my only Windows experience dates back Windows XP.

Did you install `pdftotext` as part of the Xpdf? Did you use the latest release from the official web page: https://www.xpdfreader.com/download.html ?

**Comment by bosd** [comment]
Did you get any error message?
Do the other input modules output some text?
