### ISSUE TITLE
Linesblock without end-argument possible?

### ISSUE THREAD

**Issue by RiekertKBW** [invoice-x/invoice2data#527]
Hi,

I want to get data out of a document, where the Lines-Parser can't have an end-block argument (except maybe the end of the Document).

A dedicated Start is possible, but no end.
That results in that, that the Lines-Parser can't find a block to search the lines.

For example, I have this output in the TXT-File of my PDF without any template:
```


                                     Supplier  Inc.

           Packing List                           Our Company

Nr. DDT          Del/Of    Pag.                   Streetname 12

001234           01/01/23                         12345 Cityname

Article Code                         Description                   Your Ord N  Quantity  From -> To    Boxes      U. W.

987123.7         TextForDescription      ABC123456      B12-345678       987     74       123           55  555

102345.6         DescriptionText       ABC987654      B98-765432    1.234    123   ->  456           78  910

111111.8         AnotherDescription       ABC987654      B12-345678    34    456   ->  470           14  30
```

**Comment by bosd** [comment]
Maybe you can use rexeg `\z` to match at the end of the string.

**Comment by RiekertKBW** [comment]
> Maybe you can use rexeg `\z` to match at the end of the string.

If I do \z into the end-argument, it throws an error.

`re.error: bad escape \z at position 0`

**Comment by bosd** [comment]
Maybe it is `\Z`
Maybe the example template of expressvpn will help you.
https://github.com/invoice-x/invoice2data/blob/6d8eec3619ebe749700c7520556a5ced4cb642b9/src/invoice2data/extract/templates/com/com.expressvpn_prio6.yml#L23

**Comment by RiekertKBW** [comment]
> Maybe it is `\Z` Maybe the example template of expressvpn will help you.
> 
> https://github.com/invoice-x/invoice2data/blob/6d8eec3619ebe749700c7520556a5ced4cb642b9/src/invoice2data/extract/templates/com/com.expressvpn_prio6.yml#L23

\Z worked for me, thank you very much :)
