### ISSUE TITLE
Parse field "amount" from 2 lines

### ISSUE THREAD

**Issue by stony007de** [invoice-x/invoice2data#551]
Hi

right now I try to pare the amount of an Invoice wich is in two Lines.
The fist line is the keyword the second the value.

```
valuta                                         amount_untaxed              tax-typ                        tax                  amount
06.03.2024                                        2.269,00 EUR                   19,0   %                   431,11    EUR            2.700,11    EUR
```

how can I parse, for example  "Gesamt Brutto" as  Field  **amount**?

**Comment by bosd** [comment]
You can do this with the table parser: https://github.com/invoice-x/invoice2data/blob/master/TUTORIAL.md#tables
