### ISSUE TITLE
read image pdf with tesseract falls

### ISSUE THREAD

**Issue by stony007de** [invoice-x/invoice2data#552]
Hi 

if I try to read a pdf file wiche is scannen as image. If i try to read it with the Argument "-input-reader tesseract" I get an error.

> root@sz2xd-01:/home/szadm# invoice2data --input-reader tesseract /opt/sz2xd/scan/IT-R-2024-093.pdf --debug
> INFO:invoice2data.extract.loader: Loaded 189 templates from /usr/local/lib/python3.11/dist-packages/invoice2data/extract/templates
> DEBUG:invoice2data.input.tesseract: get lang called
> DEBUG:invoice2data.input.tesseract: tesseract language arg is, deu+eng+osd
> DEBUG:invoice2data.input.tesseract: PDF file detected, start pre-processing by converting to png
> DEBUG:invoice2data.input.tesseract: temp dir is, */tmp/*
> DEBUG:invoice2data.input.tesseract: Calling tesseract with args, ['tesseract', '-l', 'deu+eng+osd', '--oem', '3', '--psm', '6', '-c', 'preserve_interword_spaces=1', '-c', 'textonly_pdf=1', 'stdin', '/tmp/IT-R-2024-093', 'pdf', 'txt']
> convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/426.
> convert-im6.q16: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3229.
> Error during processing.
> DEBUG:invoice2data.input.tesseract: Calling pdfttext with, ['pdftotext', '-layout', '-enc', 'UTF-8', '/tmp/IT-R-2024-093.pdf', '-']
> Syntax Error: Document stream is empty
> ERROR:root: Failed to extract text from /opt/sz2xd/scan/IT-R-2024-093.pdf using invoice2data.input.tesseract

**Comment by alexm96** [comment]
This might help @stony007de 
https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion
`sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml`
