### ISSUE TITLE
Prevent converting 0 to o

### ISSUE THREAD

**Issue by MisterCookie1234** [invoice-x/invoice2data#561]
Hello,

Is there a way to prevent invoice2data from changing '0' to 'o' or '.' to ','? I've tried using ocrmypdf, Tesseract, and other tools, but they all seem to have the same issue. I'm working with a scanned PDF, which is essentially an image.

**Comment by bosd** [comment]
Well, your best bet is to play with the settings of these parsers.

I have tried this before. Sometimes you can prevent it from happening by changing the dpi.
Maybe pre-process it with a tool like unpaper.


But in my cases. I couldn't prevent it from happening. To make it more robust. I have generated some regexes and used the replace method in template.
If it could be suitable for your application it could be as simple as hard replacing O with 0 (zero).

**Comment by MisterCookie1234** [comment]
Hi @bosd,

Unfortunately, simply replacing 'O' with '0' isn't a viable solution, as the number can indeed contain 'O' like in DSO000238... or DS00378O123, so it's not always a zero.

Is this issue usually caused by poor scan quality? And would it still occur if the PDFs contained text directly instead of scanned images?

**Comment by bosd** [comment]
Yes, it is totally related to poor scan quality.
I tried pre processing with unpaper.
It improved the results a lot.


You can make more specific regexes.
To replace the characters only at specific places.

If you dig trough the template examples here. There are some templates which contain a basic form of Ocr correction.
I made them after analyzing why my gas station receipts failed. 


In its current form Invoice2data replaces the characters before the parsers are called on the document.
Ideally one would have the replace function in the parser itself.
This would open up use cases like only replace the o to 0 if it is found between the start and end tag.
However this is not implemented yet.

**Comment by MisterCookie1234** [comment]
It's likely unavoidable since I've tried various OCR solutions, and the issue persists.
