### ISSUE TITLE
Add extended tests that also validates data extracted.

### ISSUE THREAD

**Issue by m3nu** [invoice-x/invoice2data#8]
Currently we run tests without looking at the data returned.

There could be some validated dicts that are compared with output data from a few files.

**Comment by sanjay-94** [comment]
How do you suggest we do this? Do you think validating the data returned based on the regex expression defined in the template is a good idea? Or should we just see if any data is returned or none is returned. I didn't quite get the concept of validated dicts you mentioned. Can you explain it ?

**Comment by m3nu** [comment]
This is the issue in question @duskybomb . You can add comments on how to best compare output here.

**Comment by duskybomb** [comment]
What I am trying to do is, I first ran the script on the pdfs in the test folder. Then I saved their data in other files which are kept in the compare folder. So, after any changes are made if we run tests, it compares the files created by the test script to the files in compare folder.

**Comment by m3nu** [comment]
We need to test:

- library
- cli functions

Both needs some sample files + expected output. I suggest 

1. Rename the test PDFs to remove spaces. Spaces often cause trouble elsewhere.
2. Make a json-file with the same name, but the `.json` extension.
3. For the test iterate over all possible test files and compare the extracted/saved values.

**Comment by duskybomb** [comment]
Can I compare two json files, test and saved one, like this?
```
    def compare_json_content(self, test_file, json_file):
        with open(test_file) as json_test_file, open(json_file) as json_json_file:
            jdatatest = json.load(json_test_file)
            jdatajson = json.load(json_json_file)
        logger.info(jdatajson)
        logger.info(jdatatest)
        if jdatajson == jdatatest:
            return True
        else:
            return False
```

**Comment by duskybomb** [comment]
I am doing json compare like this now:
```  
  def compare_json_content(self, test_file, json_file):
        with open(test_file) as json_test_file, open(json_file) as json_json_file:
            jdatatest = json.load(json_test_file)
            jdatajson = json.load(json_json_file)
        logger.info(jdatajson)
        logger.info(jdatatest)
        if jdatajson == jdatatest:
            logger.info("True")
            return True
        else:
            logger.info("False")
            return False
```

**Comment by m3nu** [comment]
I didn't test the code. You basically want a "deep comparison of dicts". I'm sure there are some best practices.

**Comment by duskybomb** [comment]
I was searching found this: https://stackoverflow.com/questions/34414326/why-is-assertdictequal-needed-if-dicts-can-be-compared-by

**Comment by m3nu** [comment]
Looks like a good answer. Please try to work independently where possible. Mentoring doesn't mean we do everything together. I can't respond to small questions 24/7.

**Comment by duskybomb** [comment]
Making a list of functions for which I need to make tests, when using invoice2data as a library:

- extract_data()
- to_json.write_to_file()

**Comment by m3nu** [comment]
Yeah. That should cover most.

- `extract_data()`
- all export functions (via comparison file?)
- pdf parsing/ocr modules
- All cli options. Partly exists.

Bonus points: Use a tool to measure test coverage and see whether we forgot something.

**Comment by duskybomb** [comment]
I thinking doing comparison will be just over-checking and unnecessary because we do compare outputs in `test_cli.py`.

**Comment by m3nu** [comment]
You can choose where to compare, but there should be one place that compares results to PDF files.

**Comment by duskybomb** [comment]
Yep, I have implemented it in `test_cli.py`

**Comment by m3nu** [comment]
Great. Then we just have:

- `extract_data()` - works as expected with arguments.
- pdf parsing/ocr modules - make sure they produce output. no need to compare the output. Since e.g. OCR is not always the same.
- cli (also compares exports and file contents)

**Comment by duskybomb** [comment]
All done sir. CI is failing with 
- pdfminer tests: pdfminer is not installed, like tesseract module is being installed
- tesseract module: because there is no matching template, as results(extracted text) are not very good.
Except these two, everything works as expected.

**Comment by m3nu** [comment]
Thanks. I'll deal with those and merge it tomorrow.

If you still have time you can get facturx working with your PDF. I suspect a field in the metadata doesn't exist in that PDF. Will be good to get to know that project.

**Comment by m3nu** [comment]
Already merged. Still adding final tests for pdfminer in branch `issue/8-2`

**Comment by duskybomb** [comment]
Should we close this?

**Comment by m3nu** [comment]
Yeah. Fine.

**Comment by duskybomb** [comment]
We can use [Coveralls](https://coveralls.io/) for coverage. What do you think?

**Comment by m3nu** [comment]
Any tool to monitor coverage is better than no tool.
