### ISSUE TITLE
Lack of templates for Indian invoice issuers

### ISSUE THREAD

**Issue by AvatarSenju** [invoice-x/invoice2data#86]
There is much lack of templates with regards to India companies which have high retail flux like flipkart and snapdeal and there may be differences in the Indian and other variants of the included firms like amazon India and Microsoft India.

PS:
So as a Solution and improvement to invoice2data I want to take this up as a project for GSoC 2018

**Comment by m3nu** [comment]
You are correct. Most templates are EU and US-focused for now. Feel free to add new templates for India. Just make a new folder with the top-level domain.

**Comment by AvatarSenju** [comment]
@m3nu I have submitted a draft proposal for this project for the Summer of Code with Google and I would humbly request you to review it.
It would be really helpful if you could provide some medium for personal contact or ping me on my email : anushrut5@gmail.com

**Comment by rmilecki** [comment]
Flipkart template has been merged, if you want / have more templates, please open a pull request.
